dhanrajdc7/Code-Overflow

- Find duplicates in given array
Given an array of n elements which contains elements from 0 to n-1, with any of these numbers appearing any number of times. Find these repeating numbers in O(n) and using only constant memory space.
> Find duplicates in given array

- sum of elements in array
Optimized Code For Getting Sum of Elements in an array quickly
> Create sum of elements in array

- FibonnaciSeries.playground/Contents.swift
- FibonnaciSeries.playground/contents.xcplayground
- VowelsConsonantsCountCalculate.playground/Contents.swift
- VowelsConsonantsCountCalculate.playground/contents.xcplayground
Fibonnaci series find in swift language using recursive method
> Fibonnaci series find using recursive method and calculate count of vowels and consonants in swift language

- print ASCII value of given character
optimized code for printing ASCII value of given character
> Create print ASCII value of given character

- print Fibonnaci Series
Optimized code for fibonacci series
> Create print Fibonnaci Series

- Factorial Of Number
Factorial of Number using Recursion
> Create Factorial Of Number

- reverse the array
> Reverse an array

- Print prime numbers in given range
Optimized code for printing the prime numbers in a given range, where upper and lower limits of the range can be provided by the user
> Create Print prime numbers in given range

- print array in reverse order
optimized code for reversing an array
> Create print array in reverse order

- find power of any number
optimized code for finding power of any number
> Create find power of any number

- Largest number in an array
Optimized code that takes input from the user and prints largest number in the array along with its position.
> Create Largest number in an array

- Multiplying matrices
Optimized code to multiply multi-dimensional arrays (including 2D and 3D arrays) with user input
> Create Multiplying matrices

- Reverse array
Optimized code to print an array (input from user) in reverse order
> Create Reverse array

- sum of elements in arrays
optimized code for getting sum of elements in an array quickly.
> Create sum of elements in arrays

- Create Smallest number
Optimized code to find the smallest number along with its position in an array
> Create Create Smallest number

- Smallest number
Optimized code to find the smallest number along with its position in an array (input from user)
> Create Smallest number

- Create check triangle is equilateral, isosceles ot scalene
optimized program to create check triangle is equilateral, isosceles ot  scalene
> Create Create check triangle is equilateral, isosceles ot scalene

- C Program for Matrix Multiplication
C Program for Matrix Multiplication Pune
> Create C Program for Matrix Multiplication

- Python program to calculate power of a given number.
Optimized code for calculating power of a given number.
>  Calculate power of a number in python

- Program to reverse the array
> Create Program to reverse the array

- Program to find factorial of number
Program to find factorial of a number
> Create Program to find factorial of number

- Program to convert binary to octal number
Program to convert binary to octal number
> Create Program to convert binary to octal number

- Program to multiply 3D Matrices
Program to multiply 3D Matrices
> Create Program to multiply 3D Matrices

- SwiftCountVowelsAndConsonants.swift
Swift implementation of counting consonants and vowels in a string.
> Create  CountVowelsAndConsonants in Swift

- finding largest of an array
solution for finding largest element of any array
> Create finding largest of an array

- finding power of any number
code for finding power of any number
> Create finding power of any number

- find prime numbers in a given range
optimized code to find prime numbers in a given range
> Create find prime numbers in a given range

- program to find smallest element of an array
program to find smallest element of any array
> Create program to find smallest element of an array

- program to print fibonacci series
optimized solution for Fibonacci series
> Create program to print fibonacci series

- program to find sum of elements in the array
code to find sum of elements of an array
> Create program to find sum of elements in the array

- program to calculate number of vowels and consonants in a string
code to count number of vowels and consonants
> Create program to calculate number of vowels and consonants in a string

- swap_case.py
this program will help you to convert all lowercase letters to uppercase letters and vice versa.
#hacktoberfest
> swap_case.py

- Find Largest Number in Array
I have used java language to create this program.
> Create Find Largest Number in Array

- RailwayReservationSystem in python.py
i create RailwayReservationSystem in python
i hope you will merge this pull request
#hacktoberfest
> Create RailwayReservationSystem in python.py

- Max value in a array
I wrote a C++ code that can be used to find the max element in the array. I used for and if loop to search and compare with max element, which initially i suppose the first one.
> Create Max value in a array

- program in java using mathematical functions
> Mathematical Function

- Simple Arithmatice Operations
I wrote a code in C++ that performs simple arithmetic operations. I used switch function to switch between different operations .
> Create Simple Arithmatice Operations

- ASCII value of Character
This is a C++ code with displays the ASCII value of the entered character.
> Create ASCII value of Character

- Program to count sum of all numbers in array
This is a program written in C++ that simply add the elements of an array and print the sum.
> Create Program to count sum of all numbers in array

- program to print prime numbers in given range
> Create program to print prime numbers in given range

- Program to multiply 2D or 3D Matrices c++
- Program to print prime numbers in given range
- program to print prime numbers in given range
Optimised code to multiply 2D or 3D Matrices  in c++
> Create Program to multiply 2D or 3D Matrices c++

- factorial program
C Program to print factorial of a number
> factorial program

- Program to find power of any number
Program to find power of any number
> Create Program to find power of any number

- Program to find length of a string
Optimized code for getting the length of a string
> Create program to find length of String

- Find largest element in array in Javascript
Efficient way to find the largest element in an array in the javascript language.
> Create Find largest element in array in Javascript

- Print leap years in given range Javascript
Most optimized way to print leap years of a range in Javascript!
> Create Print leap years in given range Javascript

- Program to reverse the array Javascript
Very efficient way to reverse an array using javascript without using array.reverse.
> Create Program to reverse the array Javascript

- Finding power of any number Java
My optimized solution to find a power of any number using Java.
> Create Finding power of any number Java

- factorial of a number
> Create factorial of a number

- largest element in an array
Program to find Largest Element in an array
> Create largest element in an array

- Smallest element in array
Program to find  smallest element in array
> Create Smallest element in array

- Largest Element in the Array
I Implemented an Optimal Java Code to Find the Largest Element Present in an Array which runs in Linear Time O(n).
> Create Largest Element in the Array

- Program to print Fibonacci series.Py
> Program to print Fibonacci

- Program to get ascii value of given character
Short code for advance problem
> program to get ascii value of character

- Program to convert binary to decimal numberdef binaryToDecimal(n):     num = n;     dec_value = 0;           # Initializing base      # value to 1, i.e 2 ^ 0     base = 1;           temp = num;     while(temp):         last_digit = temp % 10;         temp = int(temp/Program to convert binary to decimal number
Optimized code to convert binary to decimal number
> Create Program to convert binary to decimal number

- see the sum elements in array
Optimized Code for Getting Sum of Elements in an array quickly
> Create see the sum elements in array

- Binary2octal.py
> Python program to convert binary to octal

- Program to Sort an Array
This is a java program to Sort an Array using the best optimal sorting Algorithm Merge Sort which sorts the Array in O(nlogn) time Complexity.
> Create Program to Sort an Array

- array-ascending
Optimized code in python to sort the elements of an array in ascending order
> Python program to sort the elements of an array in ascending order

- Program to find factorial of number using JAVASCRIPT
here is the best method or code to find factorial of a number using JS
> Create Program to find factorial of number using JAVASCRIPT

- Java Code to print Fibonacci Series
This is the Java code that prints the Fibonacci till the Given the Number in Linear Time complexity of O(n).
> Create Java Code to print Fibonacci Series

- Java Program to Reverse An Array
This java code is the optimal program for reversing an Array which works in O(n) Time Complexity.
> Create Java Program to Reverse An Array

- Java Program to Count number of Vowels and Consonants in a String
This Java Program will print the number of vowels and Consonants in the String in Linear time i.e O(n).
> Create Java Program to Count number of Vowels and Consonants in a String

- c-lang-arithmetic-operations
Optimized C program to enter two numbers and perform all arithmetic operations
> C program to enter two numbers and perform all arithmetic operations

- Binary Search in C++ Standard Template Library (STL)
- Count distinct elements in an array
startaddress: the address of the first element of the array.
endaddress: the address of the last element of the array.
valuetofind: the target value which we have to search for.
> Create Binary Search in C++ Standard Template Library (STL)

- power-number-calculation
Optimized C Program to Calculate the Power of a Number
> C Program to Calculate the Power of a Number

- A Program to print ASCII value of given character
> Create A Program to print ASCII value of given character

- longest consecutive increasing subsequence
Hey please Accept it,,,,,!
i have added  longest consecutive increasing subsequence programme
language used:  c++
> Create longest consecutive increasing subsequence

- A Java Program to convert binary to octal number
A java program to convert the binary to octal
> Create A Java Program to convert binary to octal number

- A Program to print prime numbers in given range
An optimum and good code for to run this program
> Create A Program to print prime numbers in given range

- Write a program in C to extract a substring from a given string
An optimum code for extracting the substring
> Create Write a program in C to extract a substring from a given string

- ASCII value of given character
C++ code for printing using type conversion of char to int.
> Create ASCII value of given character

- validTriangle.cpp
Given three sides, check whether triangle is valid or not.
Approach: A triangle is valid if sum of its two sides is greater than the third side. If three sides are a, b and c, then three conditions should be met.
1.a + b > c 
2.a + c > b 
3.b + c > a
> Check whether triangle is valid or not.

- Find factorial number using Python.py
This algorithm receives a number as input and shows his factorial number.
Solution in Python 3.
> Find factorial number using Python

- check triangle
C Program to check whether the triangle is equilateral ,isosceles or scalene.
> check triangle

- Reverse elements of array
Optimized code to get reversed elements of an array
> Find Reverse elements of array

- Largest element of an array
Optimized code to find largest element of an array
> Find Largest element of an array

- Smallest element of an array
Optimized code to find the smallest element of an array
> Find Smallest element of an array

- Printing Count of Vowels and Consonants
Code written in JAVA to input a string using console and then display the number of vowels and consonants in it.
> Create Printing Count of Vowels and Consonants

- Power of a number in c++
Made a new file on problem to calculate power of any number.
> Create Power of a number in c++

- Java Program to Find Largest Element of an Array
Java Program to Find Largest Element of an Array
> Create Java Program to Find Largest Element of an Array

- To find smallest element in array
Optimiz code for smallest element in array
> Create To find smallest element in array

- Sum of number range
Optimized code for getting Sum of number range
> Create Sum of number range

- Printing Fibonacci Series
Code to Print the Fibonacci series till the number of elements desired by the user.
> Create Printing Fibonacci Series

- Java Program to Print Leap Years!
Java Program to Print Leap Years!
> Create Java Program to Print Leap Years!

- Reverse of array
Optimiz code for reverse of an array
> Create Reverse of array

- Power of a number in c++
Updated a new file named power of a number
> = Power of a number in c++

- Largest element in array
Optimiz codr for largest element in array
> Create Largest element in array

- Factorial Of Number
Made changes in the function 
Like else if statement  and the return code
> Update Factorial Of Number

- Program to reverse the array.py
- Program to reverse the array
Used Python 3.
> Program to reverse the array

- Factorial Program
THIS IS TO CREATE A PULL REQUEST FOR hacktober fest !!
> A prgm to find factorial of a number .

- Calculate all arithmetic operations in C++
Optimised code for calculation of all arithmetic operations of two numbers
> Calculate all arithmetic operations in C++

- program to find ASCII value of Character
optimize the code to find ascii value of character
> Create program to find ASCII value of Character

- count sum of all numbers in array
optimized code for getting sum of element in array with The help of python
> Create  count sum of all numbers in array

- Reverse Array in Python
Optimized and faster code to reverse array in python
> Create Reverse Array in Python

- Program to calculate power of number using javascript
this program helps you to find the power of a number using JS
-Medium level challenge
> Create Program to calculate power of number using javascript

- Program to calculate count of vowels & consonants in string
Program to calculate count of vowels & consonants in string
> Create Program to calculate count of vowels & consonants in string

- Program to print prime numbers in given range using JAVA
this program helps you to print prime numbers in a given range using JAVA
-Medium Level Challenge
> Create Program to print prime numbers in given range using JAVA

- Program to count sum of all numbers in array using javascript
This code snippet helps you to find sum of all numbers in an array using Javascript
> Create Program to count sum of all numbers in array using JavaScript

- to find factorial of number/in c
- to find factorial of number/in c++
- to find factorial of number/in java
- to find factorial of number/in python
Added program to find factorial in C++,c,python,java
> Added program to find factorial in C++,c,python,java

- Program to find smallest element in array.py
- Program to find smallest element in array
Used Python 3.
> Program to find smallest element in array (python)

- Factorial of number using c
- Largest element in array using c
- Smallest element in array using c
Created program to find factorial of a number using c language
> Factorial of number using c

- Simple interest
I have created a program for calculating simple interest using python
> Created simple interest program by python

- Program to print the ASCII value of given character
Python code to print the ASCII value of given character.
> Create Program to print the ASCII value of given character

- Finding factorial number in python
Optimized code  for finding the factorial number in python
> Create Finding factorial number in python

- finding Fabonacci Sequence in python
The optimal solution for Fibonacci Sequence in python
> Create finding Fibonacci Sequence in python

- Program to print Fibonnaci Series
Python code to print a fibonacci series of n terms
> Program to print Fibonnaci Series

- sum of two 2D matrix.cpp
Adds two 2D matrix and display their sum.
> Added sum of two 2D matrix.cpp

- Program to print Fibonacci Series using C#
to Print the Fibonacci Series up to a given number in C#
> Create Program to print Fibonacci Series using C#

- Program to count sum of all numbers in array using python
Program to count the sum of all numbers in the array using python
> Create Program to count sum of all numbers in array using python

- Program to print Fibonnaci Series in C.
Fibonacci Series with Recursion in C
> Create Program to print Fibonacci Series in C.

- Program to convert binary to decimal number using C
This program convert any binary number into decimal number
> Create Program to convert binary to decimal number using C

- Rat-Maze Problem.cpp
1. Added Rat-Maze Question with proper Problem Statement and Test cases
2. Wrote an easy and understandable code
> Create Rat-Maze Problem.cpp

- Program to print fibonacci series using c
Created program to print fibonacci series using c
> Program to print fibonacci series using c

- Program to reverse the array using c
This program is for array reversal using c.
> Create Program to reverse the array using c

- Program to calculate power of number using c
Created program to calculate power of number
> Program to calculate power of number using c

- Create program to find power of any number using python
Create a program to find power of any number using python
> Create Create program to find power of any number using python

- Program to calculate count of vowels and consonants in string
Python code to count the number of vowels and consonants in a string.
> Create Program to calculate count of vowels and consonants in string

- Program to convert from binary to decimal
Python code to convert from binary to decimal number.
> Create Program to convert from binary to decimal

- ASCII_value.py
Python program to check whether a triangle is equilateral isosceles or scalene
> Created A Python Program to Find Type of Triangle

- Program to find factorial of number using c
> Create Program to find factorial of number using c

- program to find smallest element in array using c
C program to find smallest element in array
> Create program to find smallest element in array using c

- Program to print Fibonnaci Series using c++
Print Fibonnaci Series using c++
> Create Program to print Fibonnaci Series using c++

- Program to convert binary to decimal number using python3
Program for Binary To Decimal Conversion
> Create Program to convert binary to decimal number using python3

- C Program to find smallest element in array
Program : Find Smallest Element in Array in C Programming
> Create C Program to find smallest element in array

- C Program to count sum of all numbers in array
C Program To Find Sum Of All Array Elements Using Standard Method
> Create C Program to count sum of all numbers in array

- C Program to print leap years in given range
C Program to print Leap Years between two given years!
> Create C Program to print leap years in given range

- C Program to find lenght of a string
Calculate Length of String without Using strlen() Function
> Create C Program to find lenght of a string

- Merge Sort In C
Used Divide And Conquer Approach
> Create Merge Sort In C

- Program to create factorial of two number
Optimized code for factorial of a number
> Create Program to create factorial of two number

- Program to Reverse an array
Cpp program to reverse an array
> Create Program to Reverse an array

- program to short a given array in ascending order
Optimized code for shorting a given array in ascending order
> Create program to short a given array in ascending order

- program to print leap year in given range
Optimized code for printing leap year in given range
> Create program to print leap year in given range

- program to find smallest element in array
Optimize code for printing smallest element in array
> Create program to find smallest element in array

- C++ program to display the numbers by sorting in descending order
C++ program to display the numbers by sorting in descending order
> C++ program to sort in descending order

- Fibonnaci Series/C
- Fibonnaci Series/C++
- Fibonnaci Series/Java
- Fibonnaci Series/Python
Added Java, Python, C, C++  program for Fibonacci Series.
> Added programs for Fibonnaci Series

- calculator using functions and switch-case
This is a optimized code for creating a calculator using switch-case and functions .users can easily input their numbers for calculation and choice for calculating what operations through switch-case easily.
> Create calculator using functions and switch-case

- Create program to find power of any number using python
added use of ** operator in python to find exponantional in singleline
> Update Create program to find power of any number using python

- printing Fibonacci series using recursion
Printing Fibonacci series using recursion function with C
> Create printing Fibonacci series using recursion

- Program to print prime numbers in given range using C
Program to find Prime Numbers Between given Interval
> Create Program to print prime numbers in given range using C

- a program find factorial of a number
Optimized code for getting the factorial of a number.
> Create a program find factorial of a number

- Program to print ASCII value of given character using C
Program to print ASCII Value of a character
> Create Program to print ASCII value of given character using C

- Create Program to print Prime numbers in given range using c
optimized program to print prime numbers in given range
> Create Create Program to print Prime numbers in given range using c

- Program to calculate power of number using C
Power of a Number Using the while Loop
> Create Program to calculate power of number using C

- Program to find length of a string using C
> Create Program to find length of a string using C

- a program to print the leap year in given range
Optimized code for printing leap years in a given range.
> Create a program to print the leap year in given range

- Find Largest Number in an Array
optimized solution for finding largest number in an array
> Create Find Largest Number in an Array

- a program to print total no of vowel and consonants in a string
Optimized code to print the total no of vowel & consonants in a string.
> Create a program to print total no of vowel and consonants in a string

- Program to find factorial of a number
- Program to find lenght of a string
- Program to print leap years in given range of years
Factorial in C using a for loop.
> Create Program to find factorial of a number

- Program to convert octal to binary number
Optimized code for the conversion of octal to binary number.
> Create Program to convert octal to binary number

- Program to convert binary number to octal number
optimized solution for conversion of binary to octal
> Create Program to convert binary number to octal number

- Calculate power.cpp
Program to calculate power of number
> Create Calculate power.cpp

- Program to reverse an array using C
Optimized code to reverse the elements of an array
> Create Program to reverse an array using C

- Convert Binary to Decimal number
Optimized code to convert binary number into decimal number.
> Create Convert Binary to Decimal number

- Matrix Multiplication in C
Optimized code for matrix multiplication using C
> Matrix Multiplication in C

- Addition of two matrix
Optimized code for matrix addition using C
> Create Addition of two matrix

- Create Program to print leap years in given range of years
- Program to find the length of a string
- Program to find the length of a string.
C Program to print Leap Years between two given years!
> Create Create Program to print leap years in given range of years

- Program to find lenght of a string.c
optimized code for  find lenght of a string   without Using strlen() Function
> Create Program to find lenght of a string.c

- Program to find largest element in array.cpp
Optimized code for largest element in array.cpp
> Create Program to find largest element in array.cpp

- Program to find factorial of number with c
Optimized code for factorial of number with c
> Create Program to find factorial of number with c

- Program to find smallest element in array.cpp
Optimized the code for find smallest element in array
> Create Program to find smallest element in array.cpp

- Printing Prime Numbers in the Given Range
> Printing Prime Numbers in the Given Range

- Sort given array
Code to sort given array using bubble sort
> Sort given array

- Program to find the length of a string in C
Calculated Length of String without Using strlen() Function.
> Create Program to find the length of a string in C

- Fibonnaci series
Optimized code to find fibonnaci series
> Create Fibonnaci series

- Program to find the largest element in an array in Python
Program for finding largest element in an array using python.
> Create Program to find the largest element in an array in Python

- factorial_program_python
- print_rectangle_pattern.c
C program to print solid rectangle star pattern
> Create program to print_rectangle_pattern

- Program to convert binary to decimal number_By_Ritesh_R
Change Log:
Created a new Java Program to convert Binary to Decimal
Note: please make sure to tag this pull request with Hacktober Fest, to give me a chance to win...
> Binary to Decimal in Java by Ritesh R

- Program to find lenght of a string using c
C program we are counting the number of characters in a given String to find out and display its length on console.
> Create Program to find lenght of a string using c

- Program to reverse the array in c
Program to reverse the array in c
> Create Program to reverse the array in c

- Program to count sum of all numbers in array by vedant
Given an array of integers, find sum of its elements.
Examples :
Input : arr[] = {1, 2, 3}
Output : 6
1 + 2 + 3 = 6
Input : arr[] = {15, 12, 13, 10}
Output : 50
> Create Program to count sum of all numbers in array by vedant

- Program to print Fibonnaci Series in c
C Program to print Fibonnaci Series
> Create Program to print Fibonnaci Series in c

- Program to print ASCII value of given character in c
Program to print ASCII value of given character in c
> Create Program to print ASCII value of given character in c

- Convert Binary Number to Decimal and vice-versa
In this example, you will learn to convert binary numbers to decimal and vice-versa manually by creating a user-defined function.
> Convert Binary Number to Decimal and vice-versa

- Program to find power of any number by vedant
optimized code for finding the power of a umber without using pow() function
> Create Program to find power of any number by vedant

- Program to print Fibonnaci Series by vedant
program to find the fibonacci series using python. dynamic programming 
optimized way to find fibonacci
> Create Program to print Fibonnaci Series by vedant

- Program to find factorial of number by vedant
The factorial of a positive number n is given by:
factorial of n (n!) = 1 * 2 * 3 * 4....n
The factorial of a negative number doesn't exist. And, the factorial of 0 is 1.
> Create Program to find factorial of number by vedant

- Python program to remove duplicate from list
This is the brute-force way to remove duplicate elements from a list. We will create a temporary list and append elements to it only if it’s not present.
> Create Python program to remove duplicate from list

- Python program to print Pascal's Triangle
Python Program to Print Pascal Triangle
> Create Python program to print Pascal's Triangle

- multiplication_of_ 3d _Matrix.c
this a code multiplication of 3d matrix in c language
> multiplication_of_ 3d_ matrix.c

- Python program to print table of a given number
In this program, the user is asked to enter the number, and the program prints the multiplication table of the input number using for loop. The loops run from 1 to 10 and the input number is multiplied by the loop counter in each step to display the steps of the multiplication table.
> Create Python program to print table of a given number

- Python program to find armstrong number
First Step: Take input from the user
Second Step: Find the cube of each digit of entered number
Third Step: Add the cube of all the digits
Fourth Step: If the output of step 3 is equal to the entered number i.e. Step 1. Then the print entered number is Armstrong number.
Fifth Step: If the output of step 3 is equal to the entered number i.e. Step 1. Then print entered number is not an Armstrong number.
> Create Python program to find armstrong number

- Program to find factorial of number in python
hey, this is a Optimized code of finding factorial of a number in python programming language
> Program to find factorial of number in python

- Program to calculate count of vowels & consonants in string in python
hey, this is a Program to calculate count of vowels & consonants in string in python
> Create Program to calculate count of vowels & consonants in string in python

- Program to print prime numbers in given range in python
hey this is Program to print prime numbers in given range in python
> Create Program to print prime numbers in given range in python

- Program to print Fibonacci Series in python
hey this is Program to print Fibonacci Series in python
> Create Program to print Fibonacci Series in python

- Program to find largest element in array in javaScript
This program was written in javaScript language.
> Program to find largest element in array

- to find the largest element in an array
to get the largest element in an array
> Create to find the largest element in an array

- to find the length of a string
python code for getting the length of a string
> Create to find the length of a string

- to get the smallest element in the array
to find the smallest element in the array
> Create to get the smallest element in the array

- Factorial program in c
> Factorial program in c

- Find length of a string
Optimized code for finding a length of a string
> Create Find length of a string

- Program to find length of the string in javaScript
This program was written in javaScript.
> Program to find length of the string in javaScript

- Find largest element in an array
Optimized code for finding the largest element in an array
> Create Find largest element in an array

- Hacktoberfest: Program to print leap years in given range
Code to find every leap year present in a given range.
> Create Hacktoberfest: Program to print leap years in given range

- Find factorial of a number
Optimized code for finding the factorial of a number
> Create Find factorial of a number

- Program to print the smallest element in an array
Program to print the smallest element in an array using JavaScript.
> Program to print the smallest element in an array

- Program to add sum off all numbers In an array
Calculate the sum of the elements of an array....
> Create Program to add sum off all numbers In an array

- Program to reverse the array in javaScript
This program was written in javaScript.
> Program to reverse the array in javaScript

- Java Program to sort the elements of an array in descending order
Java Program to sort the elements of an array in descending order.
> Array elements in descending order

- Hacktoberfest: Program to find factorial of number
Code for finding factorial of a positive number.
> Create Hacktoberfest: Program to find factorial of number

- Java Program to print the sum of all the elements of an array
Java Program to print the sum of all the elements of an array.
> Sum of all the elements of an array

- Program to count sum of all numbers in array in javaScript
This program was written in javaScript.
> Program to count sum of all numbers in array

- QueueUsing2Stacks1 (1).cpp
A very important interview question in AMAZON
> Queue using 2 stacks

- Factorial of a number.
It's a code for factorial of a number
> Create Factorial of a number.

- Reverse an Array using python
> Create Reverse an Array using python

- To find length of a string.
An easy code to find length of a string.
> Create To find length of a string.

- Smallest element in an array.
Easy code for finding the smallest element in an array
> Create Smallest element in an array.

- Largest element in an array.
Easy code for finding the largest number in an array
> Create Largest element in an array.

- fibonacci series in javascript.js
using recursion solving Fibonacci series
> fibonacci series in javascript

- Fibonacci series using array
adding Fibonacci series using array
> Fibonacci series in cpp

- Program to find the length of the string.
This program is used to find out the length of the string provided.
> Program to find the length of the string.

- Greater number
Program to find greatest of two numbers of c
> Greater Number

- Program to find the factorial of a number.
This is used to find the factorial of the number.
> Create Program to find the factorial of a number.

- Program to find the smallest element in array
This will print the smallest element in the array.
> Create Program to find the smallest element in array

- Finding the length of the string
finding the length of the string in python
> Create Finding the length of the string

- Hello word program
How to hello word using javascript
> Hello word program

- C++ Program to Find Largest Element of an Array
Find largest Element in an Array using C++ Program.
> Find largest Element in an Array

- C++ Program to Find the Largest and Smallest Elements in an Array
Find the Largest and Smallest Elements in an Array using C++ Program.
> Find the Largest and Smallest Elements in an Array

- C Program to Find the Length of a String
Find the length of a string using C Program.
> Find the Length of a String

- C Programming to calculate average Using Arrays
An simple example of C progarm
> Create C Programming to calculate average Using Arrays

- Please merge my pull request
C program to swap two numbers using temporary variables
> Create Please merge my pull request

- perform To perform arithmetic operations on two integers.
To perform arithmetic operations on two integers. by phython
> To perform arithmetic operations on two integers.

- Fibonacci series using c
c program for finding facrorial
> factorial of a number using c

- Program to print first N Prime numbers
Given a number N, the task is to print the first N prime number from 1 to N.
> Create Program to print first N Prime numbers

- Perfect Number
A number is a perfect number if is equal to sum of its proper divisors, that is, sum of its positive divisors excluding the number itself. Write a function to check if a given number is perfect or not.
> Create Perfect Number

- Program to check if number is even or odd
Optimized code for getting Even or Odd Number
> Create Program to check if number is even or odd

- Program to find power of any number in C Language.
Optimized Program to find power of any number In C Language
> Create Program to find power of any number in C Language.

- Program to convert binary to octal number In C Language
Optimized Code For Program to convert binary to octal number In C Language.
> Create Program to convert binary to octal number In C Language

- Program to multiply 2D or 3D Matrices
Optimized Code For Program to multiply 2D or 3D Matrices In C Language
> Create Program to multiply 2D or 3D Matrices

- binary to decimal conversion using c
c program to convert binary no. to decimal no.
> binary to decimal conversion using c

- program to calculate the no. of vowels and consonants
A C program that counts the total no of vowels and consonants
> Create program to calculate the no. of vowels and consonants

- printing the reverse of the array
optimized code for printing the elements of the array in reverse order
> Create printing the reverse of the array

- calculate power of number
optimized code for calculating the power of a number
> Create calculate power of number

- ASCII value of a character
optimized code for printing the ASCII value for any character
> Create ASCII value of a character

- Binary to decimal
optimized code for conversion of a binary number to decimal number
> Create Binary to decimal

- cpp program to find factorial of number
Optimized CPP code for getting factorial of a number.
> Create cpp program to find factorial of number

- Prime Numbers
Optimized code for Prime numbers
> Hacktoberfest- Create Prime Numbers

- Python program to find largest element in array
Optimized commented python code for finding largest element in an array
> Create Python program to find largest element in array

- array sorting in python.py
array sorting in python without using any builtin sorting function
> Create array sorting in python.py

- CPP program to find smallest element in array
Optimized cpp code for finding smallest element in an array
> Create CPP program to find smallest element in array

- Largest element in array in java
Optimized code for Largest element in array in java
> Hacktoberfest- Create Largest element in array in java

- C program to find length of a string
Optimized C code for finding length of a string
> Create C program to find length of a string

- Python program to print ASCII value of given character
Optimized code for finding/printing ASCII value of any character provided by the user.
> Python program to print ASCII value of given character

- Program to print ASCII value of given character in JAVA
Optimized Program to print ASCII value of given character
> Hacktoberfest- Create Program to print ASCII value of given character in JAVA

- Program to calculate power of number in JAVA
Optimized Program to calculate power of number.
> Create Program to calculate power of number in JAVA

- Python Program to print Fibonacci Series
Using recursion prints Fibonacci series in a single line.
> Create Python Program to print Fibonacci Series

- C program to find prime no. in a given range
C program that finds prime no. in a given range
> Create C program to find prime no. in a given range

- Program to print prime numbers in given range user input
Optimized code for Program to print prime numbers in the given range where the user provides the limits and the prime no. prints
> Create Program to print prime numbers in given range user input

- new of elements in array
Optimized Code For Getting Sum of Elements in an array quickly
> Create new of elements in array

- Python Program to convert binary to octal number
Optimized way of converting a binary number into its octal form.
> Create Python Program to convert binary to octal number

- binary to octal code
add this 
subscribed your channel
> Create binary to octal code

- factorial of any number
optimized code for calculating the factorial of a number
> Create factorial of any number

- C++ Program to Find Factorial
Program to find factorial using C++
> Program to find factorial

- SinglyLinkedList.cpp
Created Singly Linked List menu driven program with everything taken care of
> Added Singly Linked List(Menu Driven)

- Python arithmetic operations Example
This is help to do operations.
> Python arithmetic operations Example

- pressmebuttongame in c
> Create pressmebuttongame in c

- Two integer sum.
Two integer variables a and Sum.
> Two integers sum

- floydls triangle
> Create floydls triangle

- Program to Convert Binary Number to Octal  by Encryptor-Sec
- Program to check triangle is equilateral, isosceles or scalene by Encryptor
C program to calculate binary to octal and vice versa
> Create Program to Convert Binary Number to Octal  by Encryptor-Sec

- Find Sum Of All Array Elements
Find Sum Of All Array Elements Using C Program.
> Find Sum Of All Array Elements

- C Program to multiply 2D or 3D Matrices
optimized C Program to multiply 2D or 3D Matrices
> Hacktoberfest- Create C Program to multiply 2D or 3D Matrices

- Program Find Factorial of a given number
Program Find Factorial of a given number
> Create Program Find Factorial of a given number

- C Program to convert binary to decimal number
Optimized C Program to convert binary to decimal number
> Hacktoberfest- Create C Program to convert binary to decimal number

- perform all arithmetic operations
C program to perform all arithmetic operations.
> Perform all arithmetic operations

- Factor Number
C Program to Find Factors of a Number Using For Loop
> Factor Number

- Program Program to convert decimal to binary
Program Program to convert decimal to binary
> Create Program Program to convert decimal to binary

- program to find length of a given string
optimized code to find length of a given string
> Create program to find length of a given string

- Create Repeating Numbers
Optimized code for Repeating Numbers in java
> Create Create Repeating Numbers

- Python Program to count sum of all numbers in array
optimized program to count sum of all numbers in array
> Create Python Program to count sum of all numbers in array

- Python Program to find smallest element in array
Optimized Python Program to find the smallest element in array
> Create Python Program to find smallest element in array

- Multiplication of 2-D Array
Multiplication of 2-D Array using C Programming
> Multiplication of 2-D Array

- Program to Display Fibonacci Sequence by Encryptor-Sec
- Program to Find ASCII Value of a Character by Encryptor-Sec
- Program to print Fibonnaci Series by Encryptor-Sec
C program to print ASCII value of a character
> Create Program to Find ASCII Value of a Character by Encryptor-Sec

- Triangular Number pattern
Optimized code for Triangular Number Pattern
> Create Triangular Number pattern

- Count of vowels & consonants in string
Program to count the total number of vowels and consonants in a string using JavaScript
> Total number of vowels & consonants in string

- Triangular Star Pattern
Optimized Code For Triangular Star Pattern In Java
> Create Triangular Star Pattern

- Multi-dimensional Array in C
Multi-dimensional Array in C Using C Language
> Multi-dimensional Array in C

- Perform addition and subtraction of Matrices
Perform addition and subtraction of Matrices using C Language
> Perform addition and subtraction of Matrices

- Calculate the Power of a Number
Calculate the Power of a Number Using C Language.
> Calculate the Power of a Number

- HeapSort.cpp
This is Efficient sorting algorithm .
> Created HeapSort.cpp

- BinarySearch.cpp
binary search program with time complexity analysis.
> Created BinarySearch.cpp

- Factorial.cpp
Find factorial of number using both recursive and iterative way.
> Created Factorial.cpp

- CoinChangeProblem.cpp
This is a making change problem / coin change problem using dynamic programming.
> Created CoinChangeProblem.cpp

- show basic Arithmetic Operations and role of Typecasting
Show basic Arithmetic Operations and role of Typecasting Using C Language.
> Arithmetic Operations and role of Typecasting

- Reverse an Array using While Loop
C Program to Reverse an Array using While Loop Using C Language.
> Create Reverse an Array

- Display Prime Numbers Between Two Intervals
C Program to Display Prime Numbers Between Two Intervals
> Display Prime Numbers Between Two Intervals

- Calculate the Power of a Number Using Java
Java Program to Calculate the Power of a Number
> Calculate power of a number using a while loop

- python-pyramid-pattern.py
Very common beginner friendly program
> Python-pyramid-pattern program

- Python program to find largest element in the array
optimized Python program to find largest element in the array
> Create Python program to find largest element in the array

- sum of elements
optimized code for getting sum of the numbers in arrzy quickly
> Create sum of elements

- power of number
Code to calculate the power of the number
> power of number

- Large element in array
Python program to find the largest element in an array
> Find Large element in array

- convert binary to decimal number
Python program to convert a binary number to decimal number
> convert binary to decimal number

- Display ASCII value of given character
Get the ASCII value of a given character using Python
> Display ASCII value of given character

- Multiply Two Matrix Using Multi-dimensional Arrays
Multiply Two Matrix Using Multi-dimensional Arrays Using C++ Language
> Multiply Two Matrix Using Multi-dimensional Arrays

- Find Power of a Number
C Language To Find Power of a Number
> Find Power of a Number

- Print ASCII Value of a Character
C Language to Print ASCII Value of a Character
> Print ASCII Value of a Character

- counting vowels and consonants in a random input string
optimized and easily understandable way
> Counting vowels and consonants

- Adding two matrices using python
> Adding two matrices

- Subtract two matrices using python
> Subtract two matrices

- Printing power of a number using python
> printing power of a number

- Reversing array using python
> Reversing array using python

- Fibonacci_series
Write a c program to print fibonacci series without using recursion and using recursion.
> Fibonacci_series

- Prime_number
Write a c program to check prime number.
>  Prime_number

- Palindrome_number
Write a c program to check palindrome number.
> Palindrome_number

- Armstrong_number
Write a c program to check armstrong number
> Armstrong_number

- Arrays: Left Rotation
Competitive code for left rotation of array
> Create Arrays: Left Rotation

- Python Program to Find Factorial of Number Using Recursion
example of Python Program to Find Factorial of Number Using Recursion
> Create Python Program to Find Factorial of Number Using Recursion

- Counting valleys in c
got rank 1 for this code in hackerrank
> Create Counting valleys in c

- Sales by match hackerrank in c
> Create Sales by match hackerrank in c

- Find the smallest number in a given array
- java Program for factorial of a number
This program is written using java
> Create Find the smallest number in a given array

- Remove Characters in String Except Alphabets
example of Remove Characters in String Except Alphabets
> Create Remove Characters in String Except Alphabets

- Power of a number
Power / Exponent of a number using Kotlin
> Power / Exponent of a number using Kotlin

- From a C-style string
example of From a C-style string
> Create From a C-style string

- largest no in array using java
> largest no in array using java

- find power of number
optimized a code to find power of any number in python
> Create find power of number

- factorial of number java
factorial of a number using java
> Create factorial of number java

- Python program to add matrices
simple python program to add two matrices using zip method in python
> Create Python program to add matrices

- python program to print ascii value
a simple python program to find ascii value of any character using python
> Create python program to print ascii value

- Count the no. of setbits in a number
This program is about to calculating the number of setbits in the binary representation of a decimal number using all possible methods.
> Create Count the no. of setbits in a number

- Factorial program
Optimized code for getting factorial.
> Create Factorial program

- Prime number program in c
Optimized code to find prime number
> Create Prime number program in c

- Count the maximum unit of water trapped in between the buildings
It is the easiest way to calculate the amount of trapped water in between buildings.
> Create Count the maximum unit of water trapped in between the buildings

- Reverse a Number using a while loop in Java
Code to reverse a number using java
> Create Reverse a Number using a while loop in Java

- Convert decimal to binary using java
Code to convert decimal to binary using java
> Create Convert decimal to binary using java

- Euler's Method to find the highest common factor of two numbers
This is the best method of finding the greatest common divisor of two numbers
> Create Euler's Method to find the highest common factor of two numbers

- Telegram_Bot_Using_Syntaxdb_api/Telegram_Bot_Using_Sytaxdb_Api/Token.py
- Telegram_Bot_Using_Syntaxdb_api/Telegram_bot.py
- Telegram_Bot_Using_Syntaxdb_api/Token.py
- Telegram_Bot_Using_Syntaxdb_api/syntaxdb_api.py
Reverts bhubesh757/Code-Overflow#1
Telegram Bot using Syntaxdb api which
helps you to clear the coding doubts!
> Telegram Bot

- Create Fibonacci series
Optimized code for fibonacci series
> Create Create Fibonacci series

- How Operator Overloading Works ?
This is a program which completely explains how operators can be overloaded, by taking an example of subtraction operator (-)
> Create How Operator Overloading Works ?

- java program to check vowel or not
optimised  simple java programme code  to display  the entered word is vowel or not
> Create java program to check vowel or not

- How to print Swastic Pattern
This is programmatic way that how swastic pattern can be printed But there is a condition that the value of N must be odd.
> Create How to print Swastic Pattern

- Application of Josephus Problem
This is a problem where two inputs are given N and k where N is the number of peoples standing in a circle and K is the number of people you skip in each turn.
> Create Application of Josephus Problem

- Count the occurrence of distinct characters in a string
This code is about to find the frequency of each distinct character in a string
> Create Count the occurrence of distinct characters in a string

- Python program for Fibonnaci Series
An optimal python code using recursion to find the Fibonacci series of the input positive number.
> Create Python program for Fibonacci Series

- How to calculate Factorial of Large Numbers using array ?
Finding the factorial of the large numbers like 100 easily
> Create How to calculate Factorial of Large Numbers using array ?

- Kotlin ASCCI Value of Character
Kotlin ASCII value of a Character
> Create Kotlin ASCCI Value of Character

- Program to multiply 2D or 3D Matrices in c
> Create Program to multiply 2D or 3D Matrices in c

- Program to find lenght of a string in c
> Create Program to find lenght of a string in c

- Program to add 2D or 3D Matrices in c
> Create Program to add 2D or 3D Matrices in c

- BS in C++ Language
> Create BS in C++ Language

- C language program to find length of a string
C language program to find the length of a string
> Create C language program to find length of a string

- C language program Fibonacci series
C language program Fibonacci series
> Create C language program Fibonacci series

- reverse an array.
By this code, we can reverse an array.
> Create reverse an array.

- Python program to find Area of triangle
In this program, area of the triangle is calculated when three sides are given using Heron's formula.
> Create Python program to find Area of triangle

- Python program to find Compound Interest
The below formula is used to find compound interest :
A = P (1 + R/(100 * n))^nt
Here, A = The final amount i.e. intial amount + compound interest P = Principal amount or initial amount R = The yearly rate of interest n = Number of compounding periods yearly t = Number of years
> Create Python program to find Compound Interest

- Program to print prime numbers in given range in c
> Create Program to print prime numbers in given range in c

- Pattern printing Equilateral Triangle
Printing equilateral triangle using star.
> Create Pattern printing Equilateral Triangle

- Program to reverse the array.
> Create Program to reverse the array.

- Fibonacci Series python
Optimized code for Fibonacci series in python.
> Create  Fibonacci Series python

- All arithmetic operations
Optimized code for all arithmetic operations in python.
> Create All arithmetic operations

- Program of queue in c
Optimized program of queue in c
> Create Program of queue in c

- print all subsequence of a string
Code for printing all subsequences of a string using recursion.
> Create print all subsequence of a string

- Python program for factorial
Python program for factorial of a number
> Create Python program for factorial

- snake_game.c
> Added Snake Game In C

- convert binarry number to decimel
optimized code for binary to decimel
> Create convert binarry number to decimel

- Binary search tree program in c++
optimized Binary search program in c++
> Create Binary search tree program in c++

- C++ program to reverse an array
Code to reverse an array using iterative way. The time complexity of this program is O(n).
> Create C++ program to reverse an array

- Program to find factorial In C Language
Code To Find The Factorial of a Number
> Create Program to find factorial In C Language

- Code to find factorial of a number
This is a optimized code to find factorial of a number.
> Create Code to find factorial of a number

- Program to Check Triangle is Equilateral Isosceles or Scalene
Program to Check Triangle is Equilateral Isosceles or Scalene
> Create Program to Check Triangle is Equilateral Isosceles or Scalene

- Program to convert a number from binary to octal
program to convert a number from binary to octal
> Create Program to convert a number from binary to octal

- code to print Fibonacci series
This is my optimized code to print Fibonacci series of a number.
> Create code to print Fibonacci series

- Program to find largest array element in C
Optimized code to find largest array element in C
> Create Program to find largest array element in C

- FizzBuzzProblem.cpp
Added the FizzBuzz Problem solution in cpp
> Added the FizzBuzz Problem solution in cpp

- Factorial of a given number
This finds a factorial for a given number
> Create Factorial of a given number

- Length Of the String In C_Lang
I Created a Code To Find The Length Of the String
> Create Length Of the String In C_Lang

- Program to find smallest element in array In C_Lang
I Created a Code to find smallest element in array
> Create Program to find smallest element in array In C_Lang

- Program to find largest element in array In C_Lang
Optimized Code To Find The largest Element In Array In C_lang
> Create Program to find largest element in array In C_Lang

- find the sum of all element of array
Optimized Code for C program to find sum of all elements of array
> Create find the sum of all element of array

- Find the Largest Element in an array in C Lang
Optimized Code For Find the Largest Element in an array in C Lang
> Create Find the Largest Element in an array in C Lang

- Find the Largest Element in an array
Optimized Code For Finding the Largest Element in an array
> Create Find the Largest Element in an array

- find factorial of number
optimize solution for "Program to find factorial of number" in c++
> Create  find factorial of number

- add 2 array
> Create add 2 array

- add two array
> Create add two array

- find a small element in array
> Create find a small element in array

- Program to convert   binary digits to decimal digitsnumber
optimize code for conversion of binary to decimal for hactoberfest-request
> Create Program to convert   binary digits to decimal digits

- Fibonacci Series (Type-Hard)
Fibonacci Series using recursion in java
> Create Fibonacci Series (Type-Hard)

- Binary to Decimal (Type-Hard)
Program for Binary to Decimal Using Recursion in Java
> Create Binary to Decimal (Type-Hard)

- Binary to Octal (Type-Hard)
Java Program to Convert Binary Number to Octal
> Create Binary to Octal (Type-Hard)

- Check Triangle is Equilateral, Isosceles or Scalene (Type-Hard)
Program To Check whether a Triangle is Equilateral, Isosceles or Scalene in Java
> Create Check Triangle is Equilateral, Isosceles or Scalene (Type-Hard)

- Binary Search Tree
option included: 
Insert 
Print 
Clear screen
> Create Binary Search Tree

- diagonal diffrence
it is used to find the difference of the sum of two diagonals in a matrix
> Create diagonal difference

- Circular Quee
Options:
Insert(enquee)
delete(dequee)
is full
is empty
count
display
clear screen
> Create Circular Quee

- All Stack Operations
1. push
2. pop
3. isEmpty
4. isFull
5. peek
6. count
7. change
8. Display
9. clear screen
> Create  All Stack Operations

- Program to multiply 2D or 3D Matrices in c++
fully Optimized code for Create  Program to multiply 2D or 3D Matrices in c++
> Create  Program to multiply 2D or 3D Matrices in c++

- Program to Find Factorial in c++
Optimized code for Program to Find Factorial in c++
> Program to Find Factorial in c++

- Check a triangle is equilateral, isosceles or scalene
Python Program To Check a triangle is equilateral, isosceles or scalene
> Triangle is equilateral, isosceles or scalene

- Program To Convert Binary To Decimal Number in python
most optimized code Program To Convert Binary To Decimal Number in python
> Create Program To Convert Binary To Decimal Number in python

- Program To Convert Binary To Decimal Number in c++
fully optimized and fast running code for Program To Convert Binary To Decimal Number in c++
> Create Program To Convert Binary To Decimal Number in c++

- Find ASCII Value of Character
Python Program To Find ASCII Value Of Character
> ASCII Value Of Character

- Print the Fibonacci sequence
Python Program To Print the Fibonacci sequence
> Print the Fibonacci sequence

- Find power of any number
Paython Program To Calculate Power of a Number
> Calculate Power of a Number

- Create Program to Print Leap Years using java
most efficient and optimized code to Create Program to Print Leap Years using java
> Create Create Program to Print Leap Years using java

- Program to print all prime numbers in given range
optimized code for printing prime number for hactoberfest
> Create Program to print all prime numbers in given range

- Program to convert binary digits to octal digits
optimizing code for conversion of binary digits into ocatal digits for hactoberfest
> Create Program to convert binary digits to octal digits

- Program to print n number of Fibonnaci Series
optimizing code for printing fabionacci series of n numbers for hacttoberfest
> Create Program to print n number of Fibonnaci Series

- Java Program to find factorial of a number
Optimized Java program to display the factorial value of any given number
> Create Java Program to find factorial of a number

- Remove linked list elements of a particular value
If the list is 1->2->3->4 and value to be removed in 3 then list will get converted to 1->2->4 with this program. This is written in C++.
> Remove linked list elements of particular value in C++.

- Merge two sorted linked lists
By this program we can merge two sorted linked lists, like for example we have 1->3->5 and 2->4 then result new list would be 1->2->3->4->5.
> C++ program to merge two sorted lists

- Find number of unique ways to climb stairs in C++
We can take 1 or 2 steps so the number of ways in which we can reach a level n is calculated by this cpp program. This uses dynamic programming to solve the problem and has linear time and space compexity.
> C++ program to find number of unique ways to climb stairs

- Java program to calculate sum of numbers in a given array
Optimized Java Program where user can define the array and get the sum of elements in it
> Create Java program to calculate sum of numbers in a given array

- c# program to reverse an array or string
program to reverse an array or string
> Create c# program to reverse an array or string

- c# Count of Leap Years in a given year range
Count of Leap Years in a given year range
> Create c# Count of Leap Years in a given year range

- c# Prime No.
Program to find Prime Numbers Between given Interval
> Create c# Prime No.

- Power of any number
An optimized version of Java code for power function that can work for float x and negative y.
Time Complexity: O(logn)
> Create Power of any number

- Multiply Two Matrices Using Multi-dimensional Arrays
C Program to Multiply Two Matrices Using Multi-dimensional Arrays
> Multiply Two Matrices Using Multi-dimensional Arrays

- Python Program to Find Factorial of Number
Python Program to Find Factorial of Number
> Find Factorial of Number

- Java Program to find the smallest element in a given array
Optimized program to find and print the smallest element of any given array
> Create Java Program to find the smallest element in a given array

- Program  find factorial of number
Here I code factorial using the while loop in Java.
> Create Program  find factorial of number

- Java Program to find the largest element in a given array
Optimized code to find and print the largest element in a given array
> Create Java Program to find the largest element in a given array

- print Fibonnaci Series using C
C Program to Display Fibonacci Sequence
> Display Fibonacci Sequence

- Find length of string using python
code for finding the length of the string using a loop in python.
> Create Find length of string using python

- find smallest element in the array
Optimized code for finding smallest element in an array using python.
> Create a code to the find smallest element in an array

- Write a Program to find Identity Matrix in Java
A matrix is said to be an identity matrix if it is a square matrix in which elements of principle diagonal are ones, and the rest of the elements are zeroes.
> Identity Matrix

- Program  to find leap years in given range
Here I code in python. to find the leap year in the given range.
> Create Program  to find leap years in given range

- Calculate power of a number using a while loop_Java
Program to find power of a number using a while loop
> Create Calculate power of a number using a while loop_Java

- program to calculate the power of num
Here I code to find the power of any base with any exponential.I code it in the C language.
> Create program to calculate the power of num

- Python | Print number of leap years from given list of years
Python | Print number of leap years from given list of years
> Print number of leap years from given list of years

- SumOfAllNumbers_In_Array using c
Sum of all numbers in the array using recursion
> Create SumOfAllNumbers_In_Array using c

- Python Program to find sum of array
Python Program to find sum of array
> Python Program to find sum of array

- Java Program to find lenght of a string in java
> Program to find lenght of a string in java

- Find power of any number in python
Python Program to find Power of a Number using While loop or using pow function
> Find power of any number in python

- Program to count sum of all numbers in array in java
This program is in java for loop
> count sum of all numbers in array in java

- sum of elements in the array
Optimized Code For Getting Sum of Elements in an array quickly
> Create sum of elements in the array

- Program to sort given array (ascending & descending)
Optimized code for sort given array (ascending & descending)
> Create Program to sort given array (ascending & descending)

- program to find length of a string
Optimized code (to find length of a string).
> Create program to find length of a string

- Find the largest element in an array using PYTHON
Finds the largest element in the array quickly
> Find the largest element in the given array

- sum of elements in a array
> Create sum of elements in a array

- Program to find factorial of number in java
> Program to find factorial of number in java

- sum of elements in an array
> Create sum of elements in an array

- sum of elements in an array.
> Create sum of elements in an array.

- Program to find leap years
Optimized and clear code to find to leap years
> Create Program to find leap years python

- C Program to Calculate the Power of a Number
> Create C Program to Calculate the Power of a Number

- Program to Print the ASCII value of any character In PYTHON
Short and simple code to print the ASCII value of a given character in python.
> ASCII value of any character

- Program to print prime numbers in given range using python
Optimized Program to print prime numbers in given range using python
> Create Program to print prime numbers in given range using python

- total number of vowels and consonants in a string Program_java
Java Program to count the total number of vowels and consonants in a string
> Create total number of vowels and consonants in a string Program_java

- add two given Matrices_Java
Program to add two given Matrices
> Create add two given Matrices_Java

- Java_Program To Subtract Two Matrices
Java Program To Subtract Two Matrices
> Create Java_Program To Subtract Two Matrices

- Binary_to_Octal.py
- Fibonnaci_Series.py
- Power_of_Number.py
Added two more programs since last opened pull request
> Created fibonacci series and power of any number and binary to octal 

- Find the power of any number in Python
Short code to find the power of any number in Python.
> Find the power of any number

- Cpp Program to find power of any number
- Cpp Program to reverse the array
Optimized code to find the power of any number (float or integer).
> Create Cpp Program to find power of any number

- hacktoberfest-2020 - program to find nCr and nPr
[hacktoberfest-2020] a quality program for find nCr and nPr  using function
> Create hacktoberfest-2020 - program to find nCr and nPr

- C_Program to Print ASCII Value
> Create C_Program to Print ASCII Value

- C_Program to find lenght of a string
Program to find lenght of a string
> Create C_Program to find lenght of a string

- program to find largest element in array
Optimization code for( Program to find largest element in array)
> Create program to find largest element in array

- C Program for Insertion Sort
@dhanrajdc7 please check my PR.
> Updated C Program for Insertion Sort

- Print ASCII Value of Character
Wrote code to display the ASCII value of a given character.
> Create Print ASCII Value of Character

- Print Fibonacci Series
Wrote code to display the Fibonacci series
> Create Print Fibonacci Series

- Program to count sum of all numbers in array using C++
Optimized code to Program to count sum of all numbers in array using C++
> Program to count sum of all numbers in array in C++

- Program to find largest element in array using C++
Optimized code to Program to find largest element in array
> Program to find largest element in array using C++

- Program to find smallest element in array using C++
Optimized Code of Program to find the smallest element in the array
> Program to find smallest element in array using C++

- Program to count sum of all numbers in array ..
code for count sum of number in array
> Create Program to count sum of all numbers in array ..

- Program to find factorial of number using C++
Optimised code to find factorial of a number
> Program to find factorial of number using C++

- program to find length of a string in java
code for find length of a string
> Create program to find length of a string in java

- Create Looping Array Elements
> Create Looping Array Elements

- Reverse the given array in Python
Short and optimized code to find the reverse of an array.
> Reverse the given array in Python

- C++ code to count factorial of a given number
c++ code for counting factorial of a given number.
> Create C++ code to count factorial of a given number

- Create PHP Casting Strings and Floats to Integers
Create PHP Casting Strings and Floats to Integers
> Create PHP Casting Strings and Floats to Integers

- Program to find larget number in array
> Program to find larget number in array

- Program to find smallest number in array
> Program to find smallest number in array

- Power of Number-C
Used C to find the Power of any Number. Done by Aaron for Hacktoberfest.
> Create Power of Number-C

- BUBBLE SORT
> BUBBLE SORT

- Fibonnaci Series/Fibonacci Series-Recursion-C
Used recursion to solve Fibonacci Series. Language used-C . Done by Aaron for Hacktoberfest 2020.
> Create Fibonacci Series Recursion-C

- Reverse an array using pointers
In this program, we make use of * operator. 
In the reverse function, we take two pointers one pointing at the beginning of the array, other pointing at end of the array. The contents of the memory location pointed by these two pointers are swapped and then the value of the first pointer is increased and that of the second pointer is decreased.
> Reverse an array using pointers

- Program to find length of String
Lex Program to find length of a string.
Lex reads an input stream specifying the lexical analyzer and outputs source code implementing the lexer in the C programming language.
> Lex Program to find length of string

- Prime Number using Recursion
Using recursion to find whether number is prime or not
> Created program to find prime no using recurison

- Fibonacci Series Using Dynamic Programming
Optimized code for Fibonacci Series in Java using Dynamic Programming.
> Fibonacci Series in Java using Dynamic Programming

- Multiply 2D or 3D matrices
Optimized python code for multiplying 2D or 3D matrices.
> Create Multiply 2D or 3D matrices

- Count of vowel and Consonants in string
Optimized python code for calculating count of vowels and consonants in string.
> Create Count of vowel and Consonants in string

- To find the Fibonacci series in C
Optimized code to find the series of Fibonacci
> Create To find the Fibonacci series in C

- Count of Leap Years in a given year range
a fine code for count of leap years in given year range
> Create Count of Leap Years in a given year range

- Converting Binary into Decimal numbers
Optimized code to convert Binary into Decimal numbers
> Create Converting Binary into Decimal numbers

- Reverse an array in Java
a good code for reverse an array quickly
> Create Reverse an array in Java

- program for rock,paper and scissor
this is a program of rock paper and scissor
> Create program for rock,paper and scissor

- Binary To Decimal_Manas
Hey!
Saw your YouTube video and sending a PR
> Create Binary To Decimal_Manas

- C Program to Find ASCII Value of a Character
> Create C Program to Find ASCII Value of a Character

- Passing Arrays in C
> Create Passing Arrays in C

- Length of String without Using strlen() Function
> Create Length of String without Using strlen() Function

- Reverse array in half time complexity
> Create Reverse array in half time complexity

- Binary to octal using C
Convert the user entered binary number to octal and output the value
> Create Binary to octal using C

- Program to find the largest no in array in O(1) time Complexity.
O(1) sol. to find largest no in an array.
> Create Program to find the largest no in array in O(1) time Complexity.

- Sorting of array elements using quick sort in java
> Create Sorting of array elements using quick sort in java

- C Program to Sort the Array in Descending Order
C Program to Sort the Array in Descending Order
> C Program to Sort the Array in Descending Order

- Code for factorial of given number
Factorial of given number using java
> Create Code for factorial of given number

- Code for fibonacci series using java
Code for fibonacci series in java
> Create Code for fibonacci series using java

- Find factorial of number
Optimized python code for finding factorial of number.
> Create Find factorial of number

- CPP program to find largest sum contiguous subarray
CPP program to find largest Sum Contiguous subarray.
> Create CPP program to find largest sum contiguous subarray

- C Program To Enter 2 Number and Perform All Arithmetic Operations
C Program To Enter 2 Number and Perform All Arithmetic Operations
> All Arithmetic Operations

- Java Program to find power of any number
Java Program to find power of any number
> Create Java Program to find power of any number

- Power of a number(using function) in Python
Power of a number using function in Python
> Create Power of a number(using function) in Python

- Program to convert binary to octal number and vice versa
C Program to convert binary to octal number and vice versa.
> Create Program to convert binary to octal number and vice versa

- Python 3 Program to add 2D Matrices
optimized and simple Python 3 Program to add 2D Matrices
> Create Python 3 Program to add 2D Matrices

- Program for armstrong number
Optimized code for getting the armstrong numbers.
> Create Program for armstrong number

- factorialno
Program to find Factorial no. in C.
> Factorial number

- Matrix multiplication through a C++ program
Matrix multiplication program on C++ to multiply any compatible matrices and display the resultant matrix.
> Create Matrix multiplication through a C++ program

- Python 3 Program to print prime numbers in given range
optimized solution for Program to print prime numbers in given range in Python 3
> Create Python 3 Program to print prime numbers in given range

- factorial of number.c
optimized code for getting factorail.
>   factorial of number.c

- Reverse the elements of the array
Optimized code for reversing the array elements quickly.
> Create Reverse the elements of the array

- Python program for factorial of number
A python3 program using recursion to find factorial of a number using Command Line interface.
> Create Python program for factorial of number

- deleting an element in the array
Optimized code for deleting an element in the array quickly.
> deleting an element in the array

- create circular queue
Optimized code for creation of circular queue.
> Create create circular queue

- to check whether an integer is prime or not
Optimized code to check whether an integer is prime or not.
> Create to check whether an integer is prime or not

- Program for Binary To Decimal Conversion In C#
Program for Binary To Decimal Conversion in C#
> Create Program for Binary To Decimal Conversion In C#

- C_length Of String
C program to find the length of a string
> Create C_length Of String

- calculate average using array
optimized code for calculation of average using array quickly.
> Create calculate average using array

- Python script to sort and reverse the Array
Python3 script for sorting and reversing the array.
> Create Python script to sort and reverse the Array

- Program to subtract 2D or 3D Matrices
Optimized Program to subtract 2D or 3D Matrices
> Hacktoberfest-Create Program to subtract 2D or 3D Matrices

- Python Program to check Triangles
Checks the length of sides and provides the type of triangle
> Create Python Program to check Triangles

- Program to count vowels, consonants
Optimized Program to count vowels, consonants
> Hacktoberfest- Create Program to count vowels, consonants

- Python program to multiply two matrices
Using numpy library to perform multiplication of matrices
> Create Python program to multiply two matrices

- factorial program in c
program to find a factorial of a given number using a loop
> Create factorial program in c

- Factorial of number sg
- Largest element in array sg
Optimized Code for Factorial of number in C programming quickly.
> Create Factorial of number sg

- Power of a Number Using the while Loop
Optimized C Program for Power of a Number Using the while Loop
> Hacktoberfest- Create Power of a Number Using the while Loop

- Program to reverse an array
Optimized C Program to reverse an array
> Hacktoberfest-Create Program to reverse an array

- Linear search in array
> Linear search

- Add two 2D matrix
> Create Add two 2D matrix

- Find Factorial of a number (PHP)
Find Factorial of a number in php
> Create Find Factorial of a number (PHP)

- Perfect Sum probelm in java
Sum of all subsets for given sum in java
> PerfectSumProblem.java

- Program to print the Fibonacci series using python.
Optimized code for getting Fibonacci series upto n-th term using python language.
> Create Program to print the Fibonacci series using python.

- Program to find the biggest of three integer using functions
I have written a code for finding the biggest of three integers using functions in C language. It takes three inputs and gives the biggest of the three input integers as an output.
> Create Program to find the biggest of three integer using functions

- Program to add two numbers in pyhton
Optimized code for the sum of two numbers in python.
> Create Program to add two numbers in python

- Python _Code Print number of leap years from given list of years
Python Programming Print number of leap years from given list of years
> Create Python _Code Print number of leap years from given list of years

- Balanced Parenthesis by using Stacks
This C++ program, using a stack data structure, computes whether the given parentheses expression is valid or not by checking whether each parenthesis is closed and nested in the input expression.
Here is the source code of the C++ program to display if it is a balanced expression or an invalid string. This C++ program is successfully compiled and run on DevCpp, a C++ compiler.
> Create Balanced Parenthesis by using Stacks

- length of a string
Optimized code for length of a string quickly.
> Create length of a string

- Binary heap in c++
Implementation of the Binary Heap in c++ Language.
> Create Binary heap in c++

- binary to decimal conversion
Converting binary to decimal in java using method.
> Create binary to decimal conversion

- convert decimal to binary
Optimized code for conversion of decimal to binary quickly.
> Create convert decimal to binary

- Python Matrix addition
Python program to add two Matrices
> Create Python Matrix addition

- Program for Binary To Decimal Conversion c# Code
Program for Binary To Decimal Conversion
> Create Program for Binary To Decimal Conversion c# Code

- Program to multiply two matrices c# Code
Program to multiply two matrices
> Create Program to multiply two matrices c# Code

- Prime Numbers Between given Interval
Optimized code for finding the prime numbers in a given range.
> Finding Prime Numbers Between given Interval

- matrix multiplication
Optimize code for matrix multiplication quickly.
> Create matrix multiplication

- Counting number of digits in an integer
Optimized code for getting the count for entered number of digits
> Create  Counting number of digits in an integer

- Java_Program Program to find largest element in an array
Program to find largest element in an array
> Create Java_Program Program to find largest element in an array

- Write a program to calculate power_Python 3
Write a program to calculate pow(x,n)
> Create Write a program to calculate power_Python 3

- Convert a binary number to octal_Python 3
Convert a binary number to octal
> Create Convert a binary number to octal_Python 3

- [hacktoberfest] java for find modulus of a matrix
a quality code for determining the modulus of a matrix using java
> Create [hacktoberfest] java for find modulus of a matrix

- Php_Program to multiply two matrices
Program to multiply two matrices
> Create Php_Program to multiply two matrices

- c++_Program to find sum of elements in a given array
Program to find sum of elements in a given array
> Create c++_Program to find sum of elements in a given array

- C_Program to perform arithmetic operations
C program to enter two numbers and perform all arithmetic operations
> Create C_Program to perform arithmetic operations

- Fibonacci Series using Java
Optimized code for Fibonacci Series using direct formula.
Fn = {[(√5 + 1)/2] ^ n} / √5
Time Complexity: O(1)
Space Complexity: O(1)
> Create Fibonacci Series using Java

- Length of String in C_Lang
Calculate Length of String without Using strlen() Function
> Create Length of String in C_Lang

- C_Code Largest Element in an Array
C Program to Find Largest Element in an Array
> Create C_Code Largest Element in an Array

- C_Program Factorial
> Create C_Program Factorial

- Program to convert binary to decimal.c
Optimized code for converting binary to decimal
> Create Program to convert binary to decimal.c

- Fibonocci series
Optimized file for fibonocci series
> Create Fibonocci series

- Reversing the array
> Create Reversing the array

- Finding the power of any numbers
Finding the power of any numbers
> Create Finding the power of any numbers

- ASCII value
Optimized file for ASCII value
> Create ASCII value

- Program to convert lower case to upper and upper case to lower
This program using C language can convert any charecter alphabet from A-Z into lower cae if it is in upper case or vice-versa.
> Create Program to convert lower case to upper and upper case to lower

- To find the length of any string like "Shubham"
- To obtain the Fibonacci series
There is a another code for printing the fibonacci series
> Fibonacci series print

- Program to find the smallest element in an array
Optimized code to find the smallest element in an array.
> Create Program to find the smallest element in an array

- Program to find the sum of  all  element in an array
Optimized code to find the sum of all elements in an array.
> Create Program to find the sum of  all  element in an array

- Bubble sort
Optimized program for bubble sort
> Create Bubble sort

- Program to calculate count of vowels & consonants in string using C++
Optimised code to Program to calculate count of vowels & consonants in string using C++.
> Program to calculate count of vowels & consonants in string

- Program to classify a number as prime number or composite,
In this program using C language we take a input from user which can be any number and as an output we tell if the number is a priome number or a composite number.
> Create Program to classify a number as prime number or composite,

- How to reverse a number in C
Optimized program for reversing a number
> Create How to reverse a number in C

- program to print the ASCII value of a character
Optimized code in C language to print the ASCII value of a given character.
> Create program to print the ASCII value of a character

- Python program to reverse an array
Reversing the order of an array
> Create Python program to reverse an array

- Primee numbers between interval
Primee numbers between interval
> Create Primee numbers between interval
