dhanrajdc7/Code-Overflow

Matrix multiplications
=> Create Matrix multiplications

Counting number of digits in an integers
Counting number of digits in an integers
=> Create Counting number of digits in an integers

Creating a matrix multiplications
Creating a matrix multiplications
=> Create Creating a matrix multiplications

Python program to convert binary to decimal conversion
=> Create Python program to convert binary to decimal conversion

Factorial of number.py
Optimised code of factorial of number in quick way
=> Factorial.md

Dijkstras Algorithm for Single Source Path-C++
Used Dijkstra's Algorithm to find the Single Source Shortest Path in a Graph.
Done by Aaron
=> Create Dijkstras Algorithm for Single Source Path-C++

Linear Search Using Recursion-C++
Used recursion to solve linear search. Language used C++
Done by Aaron
=> Create Linear Search Using Recursion-C++

C program for febonacci siries
optimise program for fibonacci siries
=> Create C program for febonacci siries

Smallest element in array.py
Optimized code for finding d smallest element in array in a quick way
=> Smallest.md

2D Matrices  using C
optimized 2D Matrices  using C
=> Create 2D Matrices  using C

Simple interest floor and ceiling value
I have import math and used different methods of it to print ceiling and floor value.
=> Ceiling and floor value

code for ASCII
=> Create code for ASCII

left rotate array using c
=> Create left rotate array using c

valleys counting
=> Create valleys counting

java inheritance
=> Create java inheritance

Dining Philosopher Problem
Dining Philosopher Problem implemented with C language
=> Create Dining Philosopher Problem

No of nodes in BST
C++ program to find no of nodes in BST
=> Create No of nodes in BST

Deletion of BST
C++ Program for Deletion of BST(Binary Search Tree)
=> Create Deletion of BST

Graph in Data Structure
C++ Program for Implementing Graph Data Structure
=> Create Graph in Data Structure

Program to find the sum of array elements
JAVA program to find the sum of elements
=> Another Program to find the sum of array elements in JAVA

C_Program Factorial
=> Update C_Program Factorial

Binary to decimal using python
Code to convert binary to decimal in python with user input
=> Create Binary to decimal using python

Convert Decimal to Binary, Octal and Hexadecimal using python
code to convert decimal to binary, octal and hexadecimal using python taking user input
=> Create Convert Decimal to Binary, Octal and Hexadecimal using python

Program to find largest element in array using c
C program to find largest number in array.
=> Create Program to find largest element in array using c

Program to find lenght of a string using python
Python program to calculate length of a String without using len() function.
=> Create Program to find lenght of a string using python

Multiplicative Inverse using Extended Euclidean Algorithm
This code will give you multiplicative inverse of any number on any complex plane denoted and **Zq** here **q** is any number.
=> Create Multiplicative Inverse using Extended Euclidean Algorithm in Python

Program to count sum of all numbers in array using c
C program to calculate sum of all element in array.
=> Create Program to count sum of all numbers in array using c

find-lenght-of-a-string.py
=> Find length of a string

C String Initialization
=> Update C String Initialization

C++ Program for Linked List
Insert a node at any Position
Delete a node at any Position
Reverse a Linked List
Swap any two nodes in a Linked List
=> C++ Program for Linked List

Program to find power of any number using c
C program to find power of any number using recursion
=> Create Program to find power of any number using c

Print leap year in a given year range
Improved program of leap year in given range
=> Print leap year in a given year range

Invisibility using Python
It is an OpenCV project. It is the working example of, "The Invisibility Cloak" from Harry Potter, series.  It uses some basic concepts of Image Processing. It will make the area with red part, invisible.
=> Create Invisibility using Python

Program to reverse the array element
A C++ Program to reverse the array element
=> Create Program to reverse the array element

A star.py
Added code in Python for the Informed search algorithm (A* algorithm), which is used in AI basics.
=> Created Informed search algorithm (A* algorithm)

Program to Convert Binary to Decimal
Optimized program to convert the binary number to decimal
=> Binary to Decimal Program

A C++ Program to print ASCII value of given character
A C++ Program to find the ASCII value of any character
=> Create A C++ Program to print ASCII value of given character

String Operation using Java
Given two strings, append them together (known as "concatenation") and return the result. However, if the strings are different lengths, omit chars from the longer string so i
=> Create String Operation using Java

Python Program to convert binary to decimal number
A Python program for converting any binary number to the decimal number .
=> Create Python Program to convert binary to decimal number

Menu Driven-Calculate Basic Arithmatic Operations
This is a menu driven program to calculate all the basic arithmatic operations in c programing language
=> Create Menu Driven-Calculate Basic Arithmatic Operations

Matrix addtion
Program to perform matrix addition
=> Matrix addition

Program to reverse the array in Java Language
I have Created A Program to reverse the array in Java Using Eclipse
=> Create Program to reverse the array in Java Language

Program to print the fibonacci series -C++
This is a simple c++ program which will print the fibonacci series given number of terms
=> Create Program to print the fibonacci series -C++

Calculate compound interest, Calculate compound interest.java
Please accept my PR and mark it as Hactoberfest accepted
=> Calculate compound interest 

Print leap years in given range of numbers
C program to print the leap years in range n1 to n2
=> Print leap years of given range

Program to find largest element in array in Java Using Eclipse
Program to find largest element in array in Java Using Eclipse.
=> Create Program to find largest element in array in Java Using Eclipse

Simple Calculator in Bash Language  Using Ubuntu Terminal
Me Indrajit Sinha Simple Calculator in Bash Using Ubuntu Terminal.
=> Create Simple Calculator in Bash Language  Using Ubuntu Terminal

Array Reversed
A simple program written in C to reverse an array.
=> Array Reversed

Difference between Sum of Square using Java
Write a program to find the difference between sum of the 
//squares and the square of the sums of n numbers? 
//Sum of the square(n) ,square of sum n//
=> Create Difference between Sum of Square using Java

ASCII value print
A simple C program to print ASCII value
=> ASCII value print program

Number raised to a power
Power of a number using binary exponentiation algorithm.
=> Create Number raised to a power

Palindrome program in C
code to find palindrome using c
=> Create Palindrome program in C

Fibonacci Series in C
optimized code to find fibonacci series.
=> Create Fibonacci Series in C

Armstrong Number in C
code to create armstrong number
=> Create Armstrong Number in C

C Program to print Alphabet Triangle
To print alphabet triangle using c programming language.
=> Create C Program to print Alphabet Triangle

rogram to convert binary to decimal number
=> Create rogram to convert binary to decimal number

Constraint Satisfaction Problem - Graph coloring.py
Added code in Python for Constraint Satisfaction Problem - Graph colouring, which is used is AI basics.
=> Created Constraint Satisfaction Problem

Arithmetic calc
Added a program to calculate all arithmetic operations python!
=> Arithmetic operations python

count vowels and consonants
added a python code that can count the number of vowels and consonants!
=> Create count vowels and consonants

Program to find largest element in an array
=> Create Program to find largest element in an array

Program to find smallest element in an array
=> Create Program to find smallest element in an array

Program to find sum of all elements in an array
Sum of all elements in an array
=> Create Program to find sum of all elements in an array

Segment trees
the most optimal way of representing data.
=> Create Segment trees

persistent Segment trees
the optimal data structure of retrieving element.
=> Create persistent Segment trees

Leap year
Python program to check leap year
=> Program to check Leap year

LinkedHashSet Class In java
=> Create LinkedHashSet Class In java

Best First Search.py
Added code in Python for the Best first search algorithm, which gives the best solution but not always optimal.
=> Created Best first search algorithm

Fibonacci Series In C++
Hard Problems(Fibonacci Series)
=> Create Fibonacci Series In C++

Replace all 0(s) with 5(s) in user accepted number
This is a python code for a program where a user enters a number and the job of the code is to convert all 0(s) to 5(s) in that number and print that number.
=> Create Replace all 0(s) with 5(s) in user accepted number

Wave Print in 2D-Array
This is a C++ Code for which a 2D array is used to print in an alternate (wave-like) pattern without using any STL.
=> Create Wave Print in 2D-Array

Spiral Print of a 2D Array
In this Code I'm printing a 2D Array in Spiral fashion, i.e Printing Odd rows normally and then Even rows in opposite order (i.e from last column to first column) and continuing till the last row.
=> Create Spiral Print of a 2D Array

Finding nth root of a number using C++.
A tricky but not tough, this is the code implementation of nth root of a number using C++.
=> Create Finding nth root of a number using C++.

Program to check triangle is equilateral, isosceles ot scalene
Program to check triangle is equilateral, isosceles ot scalene
=> Create Program to check triangle is equilateral, isosceles ot scalene

Program to print ASCII value of given character with python
Program to print ASCII value of given character with python
=> Create Program to print ASCII value of given character with python

Program to convert binary to octal number with python
Program to convert binary to octal number with python
=> Create Program to convert binary to octal number with python

Create a program to find lenght of a string length in javascript.js
Create a program to find lenght of a string length in javascript.js
=> Create a program to find lenght of a string length in javascript.js

Length of String
Here i have directly used built in function it will somehow save some of the lines and time complexity.
=> Create Length of String

Binary Search Tree
updated optimized binary search tree code in python
=> Update Binary Search Tree

Program to add two numbers in pyhton
=> Update Program to add two numbers in pyhton

A string is palindrome or not
Optimized code to check whether a string is palindrome or not.
=> Create A string is palindrome or not

ps3_hangman.py
If you've played scramble , this is an online version of it !
=> Game of Scrambled Words

Fibonacci series in java
created a program on the Fibonacci series in java language.
=> Added a program on Fibonacci series in java

python Program to reverse the array
python Program to reverse the array in three different methods
=> Create python Program to reverse the array

python program to calculate power of number
python program to calculate power of number using for loop
=> Create python program to calculate power of number

Fibonnaci Series/Java Use Dynamic Programming
added code Fibonacci Series using Dynamic Programming
=> Create Java Use Dynamic Programming

C Program to Find Largest Element in an Array
This program takes n number of elements from the user and stores it in arr[].
To find the largest element,
the first two elements of the array are checked and the largest of these two elements are placed in arr[0]
the first and third elements are checked and the largest of these two elements is placed in arr[0].
this process continues until the first and last elements are checked
the largest number will be stored in the arr[0] position
=> C Program to Find Largest Element in an Array

C Program to Swap Two Numbers
In the above program, the temp variable is assigned the value of the first variable.
Then, the value of the first variable is assigned to the second variable.
Finally, the temp (which holds the initial value of first) is assigned to second. This completes the swapping process.
=> Create C Program to Swap Two Numbers

C Program to Generate Multiplication Table
In this code, I have limited the multiplication table range to 10.  You can modify the code by changing the range (i).
=> Create C Program to Generate Multiplication Table

python Python program to sort an array in descending order
python program to sort an array in descending order
=> Create python Python program to sort an array in descending order

C program to Reverse a Sentence Using Recursion
This program first prints Enter a sentence. Then, the reverseSentence() function is called.
This function stores the first letter entered by the user in c. If the variable is any character other than \n (newline), reverseSentence() is called again.
This process goes on until the user hits enter.
When the user hits enter, the reverseSentence() function starts printing characters from last.
=> Create C program to Reverse a Sentence Using Recursion

Python Program to Check Leap Year
You can change the value of year in the source code and run it again to test this program.
=> Create Python Program to Check Leap Year

elements sum in array
code for sum of elements in array in c.
=> elements sum in array

largest element of a array
How to easily find out largest element in a array using c
=> largest element in array

BUBBLE SORT UPDATED
This is some updated Code for Bubble sort
=> Create BUBBLE SORT UPDATED

GoogleChart.md, Google_Chart.md
=> google Chart Added

Program to print ASCII value of given character.md
=> Create Program to print ASCII value of given character.md

C Program to find largest element in array
optimized code for finding largest element in a user-defined  array.
=>  C Program to find largest element in array

Largest element in a given array with Python
Program for getting the largest element in an array with Python
=> Create Largest element in a given array with Python

Program to print ASCII value of given character in C++
Efficient way to print ASCII value of given character in most popular language c++.
=> Create Program to print ASCII value of given character in C++

program to print fibonacci series recursively
added recursive method to print fibonacci series
=> Create program to print fibonacci series recursively

Counts of vowel and consonant in a string
Optimized code for calculating counts of vowel and consonant in a string with Python.
=> Create Counts of vowel and consonant in a string using Python

program to print ASCII value of given character
Optimized code for printing ASCII value of given character
=> Create program to print ASCII value of given character

Program to convert binary to decimal number Pre-define Function/Program to convert binary to decimal number in C
Program of Convert Binary to Decimal number in C language. I saw this program in your repository but in that program input is taken by user so I update it in most efficient way.
=> Create Program to convert binary to decimal number in C

Leap years in a given range using Python
A Program For Counting the Number of Leap Years In a Given Range With Python
=> Create Leap years in a given range using Python

Reverse the array using Python
Program For Reversing Items In An Array Quickly With Python
=> Create Reverse the array using Python

Convert binary to octal using Python
Short Code For Converting Binary To Octal Quickly With Python
=> Create Convert binary to octal using Python

Programm to print Prime numbers in given range
This is a updated Code for Finding Prime number  in a given range
=> Create Programm to print Prime numbers in given range

C Program to Convert Binary to Decimal
This is Updated C Code for Conversion of Binary No to Decimal No
=> Create C Program to Convert Binary to Decimal

Calculate count of vowels & consonants in string
Optimized code in Java to count number of vowels and consonants in string
=> Create Calculate count of vowels & consonants in string

Length of String in Java
Optimized code to find length of string in java
=> Create Length of String in Java

C Program to Display Fibonacci Sequence
=> Create C Program to Display Fibonacci Sequence

program to reverse an array recursively
added a recursive method to reverse an array
=> Create program to reverse an array recursively

Program to convert binary to decimal number/ProgramToConvertBinaryToDecimalNumber.cpp, array reverse, binary to decimal converter, binary to octal, create power of numbers, css/style.css, factorial of numbers, fibonacci series in c, find the length of the string, matrix multiplication 2D, series in c
=> factorial of no

Program to print prime numbers in a given range
added a efficient solution to print prime numbers
=> Create Program to print prime numbers in a given range

program to find factorial of a given number recursively
added a method to recursively find factorials of a number
=> Create program to find factorial of a given number recursively

Program to convert binary to octal number in C
Most effective way to convert Binary to Octal Number in C language.
=> Create Program to convert binary to octal number in C

Program to find smallest array element in C
Optimized code for program to find smallest array element
=> Create Program to find smallest array element in C

C Program to Check Leap Year
Optimized code for Program to print leap years in given range
=> Create C Program to Check Leap Year

C Program to subtract 2D or 3D Matrices
Optimized code to subtract 2D or 3D Matrices
=> Create C Program to subtract 2D or 3D Matrices

C Program to Convert Binary Number to Octal and vice-versa
Optimized code to Convert Binary Number to Octal and vice-versa
=> Create C Program to Convert Binary Number to Octal and vice-versa

sum of elements in arrayss
optimized code for sum of elements in array
=> Create sum of elements in arrayss

Finding Smallest element in an array
Optimized C++ code for finding the smallest element in an array.
=> Create Finding Smallest element in an array

An Optimized C++ Program to print ASCII value of given character
Optimized Code for Printing ASCII value of given character in C++.
=> Create An Optimized C++ Program to print ASCII value of given character

{hacktoberfest} palindrome cheaking using java
a simple and qualitative code to check palindrome or not using stack using java
=> Create {hacktoberfest} palindrome cheaking using java

Fibonacci Seriess
Fibonacci Series algorithm in c++
=> Create Fibonacci Seriess

Binary conversion to deci
=> Create Binary conversion to deci

Largest item in array Java
Finding largest item in array . Java language
=> Create Largest item in array Java

Fibonnaci Series/Program for Fibonacci numbers Using formula.java
Added the new optimized code for  Program for Fibonacci numbers
In this method we directly implement the formula for nth term in the fibonacci series.
Fn = {[(√5 + 1)/2] ^ n} / √5
=> Create Program for Fibonacci numbers Using formula.java

comparision between two different strings
java program to find the difference between two strings
=> Create comparision between two different strings

Sum of node values of a simple path is not divisible by length
Sum of node values of a simple path is not divisible by length
=> Create Sum of node values of a simple path is not divisible by length

Magic Number
You are given two integers L
and R
. Find the smallest non-negative integer N
such that
N%L>N%(L+1)>…>N%(R−1)>N%R.
=> Create Magic Number

Fast way to calculate Nth Fibonacci number
=> Create Fast way to calculate Nth Fibonacci number

Check whether a Triangle is Equilateral, Isosceles or Scalene
Program To Check whether a Triangle is Equilateral, Isosceles or Scalene
=> Create Check whether a Triangle is Equilateral, Isosceles or Scalene

arithmetic operations in c language
=> Create arithmetic operations in c language

Program to multiply 2D or 3D Matrices in java
program to multiply 2d or 3d matrices in java
=> Create Program to multiply 2D or 3D Matrices in java

Program to find lenght of a string in c and c++
Program to find lenght of a string
=> Create Program to find lenght of a string in c and c++

program to print ascii value of given character in java
program to print ascii value of given character in java
=> Create program to print ascii value of given character in java

prime number
=> Create prime number

Largest_Element_of_Array/c, Largest_Element_of_Array/cpp, Largest_Element_of_Array/python
Added some program  to find largest number in Array
=> Added program  to find largest number in Array

Program_to_print_leap_years/c, Program_to_print_leap_years/cpp, Program_to_print_leap_years/python
Added codes for some program to print leap year
=> Added codes for program to print leap year

Count sum of all numbers in an array in JAVA
Optimized code to find sum of elements in an array in Java language
=> Create Count sum of all numbers in an array in JAVA

Program to find factorial of number using Recursion
Created a program to find factorial of number Using Recursion.
=> Create Program to find factorial of number using Recursion

Get ASCII Value of the given input of Character
Get the ASCII value of the given input character .
=> Create Get ASCII Value of the given input of Character

program to print ascii values of charachter
simple optimised code of ascii values od charachter
=> Create program to print ascii values of charachter

program to find the factorial of a number
this is a code to print factorial recursively
=> Create program to find the factorial of a number

this is a program to print fibonacci series
this is a simple iterative way to print fibonacci series
=> this is a new program to print fibonacci series

this is a new program to print reverse of an array
This is a simple program to print rev of array using functions
=> Create this is a new program to print reverse of an array

Factorial of number Entered by user
=> C Program to Find Factorial of a Number

Code to find power of any number
Code to find the power of any number using loop.
=> Create Code to find power of any number

Print Fibonacci series in JAVA
Optimized code to print Fibonacci series.
=> Create Print Fibonacci series in JAVA

To check if a triangle is equilateral, isosceles or scalene
Optimized code to che the eligibility of a triangle to be equilateral, isosceles or scalene
=> Create To check if a triangle is equilateral, isosceles or scalene

Merge Sort in C language
Code for doing MergeSort operation on an array of integers in C language
=> Merge Sort in C language

Quick Sort in C language
Code to run QuickSort operation on an array of integers in C language
=> Quick Sort in C language

Search element in a randomly generated list
Code to generate a random list of integers and search if a user-input number is present in the list or not (C language)
=> Search element in a randomly generated list (C)

Linked List operations (C)
Basic operations for Linked List in C language
=> Linked List operations (C)

Generate Fibonacci Series in C
Generating Fibonacci Series upto n number of terms defined by user input
=> Generate Fibonacci Series (in C)

Prime Number or Not
Enter a number to find out if it is prime or not
=> Prime Number or Not

C++ Program to Find All Roots of a Quadratic Equation
C++ Program to Find All Roots of a Quadratic Equation
=> Create C++ Program to Find All Roots of a Quadratic Equation

C++ Program to Find GCD
=> Create C++ Program to Find GCD

Program to find factorial of number in javaScript
Program to find factorial of number in javaScript
=> Create Program to find factorial of number in javaScript

Program to count sum of all numbers in array with javaScript
Program to count sum of all numbers in array with JavaScript
=> Create Program to count sum of all numbers in array with javaScript

finding factorial of number, to find largest element in an array
first pull request for hacktober fest
=> Create finding factorial of number

Sum of elements in list (python)
Sum of elements in an array  represented by a list in python
=> Create Sum of elements in list (python)

Length of string in python
=> Create Length of string in python

Factorial Number
=> Create Factorial Number

Minimum element in array using java
Optimized code to find minimum element in array quickly
I have done the code using java language
=> Create Minimum element in array using java

Maximum element in array using java
Optimized Code to find Max element in array quickly
I have done this code using java
=> Maximum element in array using java

Program to calculate power of number (python)
=> Create Program to calculate power of number (python)

Program To Print Fibonacci series in C language
**Kindly merge this PR. Doing this as a part of Hacktoberfest**
=> Program To Print Fibonacci series in C language

Reverse an array using java
Optimized code for reversing an array quickly
I have done it using java
=> Reverse an array using java

Sum of all elements in array
Optimized code for finding sum of all elements in array quickly
I have done it using java
=> Create sum of all elements in array

print leap year in given range using java
optimized code to find leap year in given range quickly
i have done it using java
=> print leap year in given range using java

Program to convert binary in C lang to decimal number
=> Program to convert binary in C lang to decimal number

Program to convert binary to octal number in C lang
Optimized Code kindly merge the PR for HacktoberFest
=> Program to convert binary to octal number in C lang

To check a number is armstrong or not
Optimized code to check whether a number is Armstrong or not
=> Create To check a number is Armstrong or not

gussTheNumber.c
This will be a number guessing game that will randomly generate number between 1 to 100, User will enter number if entered number is greater or lesser it will give prompt to enter smaller or grater number respectively, At the end it will tell us about number of steps taken by us.
=> Number Guessing  Game

c program to add 2d matrix, code to find factorial of number
optimized code to find the factorial of a number quickly.
=> to find the factorial of a number

Python Program to find the area of triangle
In this program, area of the triangle is calculated when three sides are given using Heron's formula.
If you need to calculate area of a triangle depending upon the input from the user, input() function can be used.
=> Create Python Program to find the area of triangle

Tiles game
=> Tiles Game

Circular Linked List.cpp
A cpp program to Insertion 
A node can be added in three ways: Insertion in an empty list
Insertion at the beginning of the list
Insertion at the end of the list
Insertion in between the nodes
and
, alter , sort, search in  a circular linked list.
=> Circular Linked List

Flappy Game
Flappy Game using Python
#1062
=> Flappy Game

Program to reverse function the array in c
I have made reverse code for the program
=> Create Program to reverse function the array in c

Cannon Game
=> Cannon Game

to find factorial of a number
Hii, I am Aman Sharma. This is the C language code to find the factorial of  a number.
=> Create to find factorial of a number

sum of all numbers in array
optimized code for getting sum of in array
=> Create sum of all numbers in array

Code :Program to find length of a string
Optimized code for finding the length of a string.
=> Create Code :Program to find length of a string

Python program to find second largest number in a list
I have explained all the attempts in code :)
=> Create Python program to find second largest number in a list

Python | Remove empty tuples from a list
I have explained  all the attempts in code :)
=>  Python | Remove empty tuples from a list

Python program to convert a list to string
I have explained all the attempts on code :)
=>  Python program to convert a list to string

smallest element in an array
=> Create smallest element in an array

BFS_graphTraversal.py
Adding Breadth First Search Graph Traversal Algorithm using adjacency list in python.
=> BFS_GraphTraversal Algorithm

Codes to convert a number from binary to octal
I have added the codes to convert a number from binary to octal in the following languages: 
Python
C
C++
Java
=> Create Codes to convert a number from binary to octal

Easy program to reverse an array
Code to reverse an array in C language.
=> Create Easy program to reverse an array

Find the largest element in an Array
=> Find the largest element in an Array

Find the smallest number in an Array
With best time and space complexity using cpp
=> Create Find the smallest number in an Array

count of vowels & consonants in string
cpp code valid for both upper and lower case
=> Create count of vowels & consonants in string

snakeWaterGun.c
Snake, water and gun like Stone, Paper and Scissor.
=> Snake, Water and Gun Game

convert binary to octal number
=> Create convert binary to octal number

Program to find length of a string in C
=> Create Program to find length of a string in C

Program to find power of any number in C
=> Create Program to find power of any number in C

To delete an element from an array
Optimized code to delete an element from an array.
=> Create To delete an element from an array

Pythone password Generator
All attempts described in codes :)
=>  Python password Generator

optimized code for getting length of a string quickly
optimized code for getting length of a string quickly
=> Create optimized code for getting length of a string quickly

optimized code to get largest element in array
optimized code to get largest element in array
=> Create optimized code to get largest element in array

optimized code to get vowels & constants in string quickly
optimized code to get vowels & constants in string quickly
=> Create optimized code to get vowels & constants in string quickly

optimized code to get binary to decimal number quickly
optimized code to get binary to decimal number quickly
=> Create optimized code to get binary to decimal number quickly

C++ Program to find power of any number
Code for finding the power of any number quickly.
=> Create C++ Program to find power of any number

Recursive Binary Search using C++ Program
Code for Binary Search Using Recursion
=> Create Recursive Binary Search using C++ Program

Min_Max.java
Given A Series Of **N** Positive Integers a1,a2,a3........an. , Find The Minimum And Maximum Values That Can Be Calculated By Summing Exactly **N-1** Of The N Integers. Then Print The Respective Minimum And Maximum Values As A Single Line Of Two Space-Separated Long Integers.
=> Min_Max of N-1 element

Calculate power using pow() Function, Print ASCII value of character in c++
=> Create Print ASCII value of character in c++

fibonacci series printing
program for print of fibonacci series in phython language
=> Create fibonacci series printing

Linked Lists using C++
Optimized code for Linked Lists using C++
=> Create Linked Lists using C++

2D or 3D Multiply using C++ Program
Code for Multiplying 2D and 3D array in C++
=> Create 2D or 3D Multiply using C++ Program

Using Recursion Finding Fibonacci Series
Fibonacci Series Using Recursion
=> Create Using Recursion Finding Fibonacci Series

sum of elements of arrayy
=> Create sum of elements of arrayy

Find Leap year, Find greater number, Find power of any number in python., Pascal's triangle
Here is a  C Program to Find Largest of Two numbers.
=> Find greater number

Binarysearch in java
Optimized code for searching an element using binary search
=> Create Binarysearch in java

Linkedlist in java
Optimized code for a Linked list
=> Create Linkedlist in java

Merge sort in java
Optimized code for Merge Sort in Java
=> Create Merge sort in java

Insertion sort in java
Optimized code for Insertion sort in Java
=> Create Insertion sort in java

To find fibonacci for BigInteger in Java
=> Create To find fibonacci for BigInteger in Java

prime check
=> Create prime check

Java Program to find power of any number using recursion
Java Program to find power of any number using recursion
=> Create Java Program to find power of any number using recursion

Java Program For Array Manipulation
Java Program For Array Manipulation
=> Create Java Program For Array Manipulation

Java Program to find factorial of BIG INTEGER
Java Program to find factorial of BIG INTEGER
=> Create Java Program to find factorial of BIG INTEGER

add_2D_matrices.c
Code to add 2 two dimentional matrices.
plz help me.
Please merge my pull request and add hactoberfest label.
=> sum of 2 2d matrices in c

Bubble sort in Java
Optimized code for Bubble Sort in Java
=> Create Bubble sort in Java

Insertion Sort in Python
Optimized Code for Insertion Sort in Python
=> Create Insertion Sort in Python

DFS in Java
Optimized code for DFS in Java
=> Create DFS in Java

Largest_Element_of_Array/Last_element.c
Display last element of an array
=> Display last element of an array

factorial/factorial_recursion.dart
recursive program in dart to find factorial of a number
=> factorial of a number using recursion in dart

Program_to_print_leap_years/leap_year.dart
Dart program to check for prime number.
Please accept my pr.
=> check for leap year using dart

Caluculator in C
Optimized code for Calculator Program in C language
=> Create Calculator in C

Swap Two Integers without using third variable in C
Optimized code for swapping two integers without using third variable
=> Create Swap Two Integers without using third variable in C

Program to check triangle is equilateral, isosceles or scalene.c
hello, There 😃  I  choose  problem statement from hard level
Program to check triangle is equilateral, isosceles or scalene
and written condensed code 💩
=> Create Program to check triangle is equilateral, isosceles or scalene.c

Program to convert binary to octal number.c
hello, There 😃 I choose problem statement from hard level
Program to convert binary to octal number
and written condensed code 💩
=> Create Program to convert binary to octal number.c

Program to print prime numbers in given range.c
hello, There 😃 I choose problem statement from medium level
Program to print prime numbers in given range
and written condensed code 💩
=> Create Program to print prime numbers in given range.c

check triangle is equilateral, isosceles
Program to check triangle is equilateral, isosceles or scalene.
=> Create check triangle is equilateral, isosceles

Number guessing game
This is a Number Guessing Game.
=> Number guessing Game

python_find_largest_element_in_array_fastest_method
Fastest program to find largest element in array made in python, its cool because you can write unlimited count of numbers , and it would be working under one second :D
=> Fastest program to find largest element in array

Optimized solution for Program to find length of a string
Optimized code for find length  of string
=> Create Optimized solution for Program to find length of a string

Program to find largest element in array (arbaaz29)
optimized code for largest number
=> Create Program to find largest element in array (arbaaz29)

Optimized Reverse an array in Java
=> Create Optimized Reverse an array in Java

Java Program to Display Fibonacci Series easy solution
Java Program to Display Fibonacci Series easy solution
=> Create Java Program to Display Fibonacci Series easy solution

preorder
=> created preorder

JAVA 8 Program for Binary To Decimal Conversion
JAVA 8 Program for Binary To Decimal Conversion
=> Create JAVA 8 Program for Binary To Decimal Conversion

max sum
=> created max sum

Program to find smallest element in array(arbaaz29)
optimized code for smallest number
=> Create Program to find smallest element in array(arbaaz29)

Program to reverse the array(arbaaz29)
optimized code for reversing an array
=> Create Program to reverse the array(arbaaz29)

dp function
=> created dp function

linklist
=> created linklist

Program to calculate all arithmetic operations
optimized code for calc, needs little help with mod
=> Create Program to calculate all arithmetic operations

Fibonacci Series - Suvechchha Pal
Optimized code for printing Fibonacci Series in an easy way.
=> Create Fibonacci Series - Suvechchha Pal

Count sum of all elements in an array
Optimized code to count the sum of all the elements in an array efficiently and easily.
=> Create Count sum of all elements in an array - Suvechchha Pal

Find largest element in an array - Suvechchha Pal
Optimized code to find the largest element in an array efficiently.
=> Create Find largest element in an array - Suvechchha Pal

Program to find factorial of number_dikshant
adding my experience to hacktoberfest.
=> Program to find factorial of number_dikshant

Program to print Fibonnaci Series_dikshant
Fibonacci series program, adding my experience to hacktoberfest.
=> Create Program to print Fibonnaci Series_dikshant

Program to count sum of all numbers in array_dikshant
adding my experience to hacktoberfest.
=> Create Program to count sum of all numbers in array_dikshant

Program to find length of a string_in_c
=> Create Program to find length of a string_in_c

BFS in C
=> Create BFS in C

Program to calculate count of vowels & consonants in string in JavaScript.js
Program to calculate count of vowels & consonants in string in JavaScript
=> Added program solution

FizzBuzz in Python
Optimized code for Fizz Buzz problem in Python
=> Create Fizz Buzz in Python

AVL tree in Python
Optimized code for AVL tree Operations in Python
=> Create AVL tree in Python

Second smallest element in list
Optimized code to find second smallest element in list
=> Create Second smallest element in list

Implement Stack using Queue
Optimized code to implement Stack using Queue
=> Create Implement Stack using Queue

Program to find the largest element in array _Java
Used java to find the largest element in an array
=> Create Program to find the largest element in array using  _Java

Python program to calculate length of a string in __python
Contributed to the program to count the length of a string
=> Python program to calculate length of a string in __python

Calculate Power of a number
Hello sir , This file contains a C program to "calculate the Power of a number". Thank you.
=> Create Calculate Power of a number

Find ASCII value of a character
Hello sir , This file consist a C Program to "Find ASCII value of a character". Thank you.
=> Create Find ASCII value of a character

C++ program to check the number of leap year in given range
Added my contribution to this program. Please merge the request. Thanks in advance.
=> C++ program to check the number of leap year in given range

C program to find factorial of a number in __C
Added my contribution. Please oblige me by merging it. Thanks in advance.
=> C program to find factorial of a number in __C

Program to reverse the array with the help of loop in java and not reverse method
=> Create Program to reverse the array with the help of loop in java

sum of all numbers in an array
Hello, This file consist of a program in c to "find the sum of all numbers in an Array".
=> Create sum of all numbers in an array

Prime number using Sieve of Eratosthenes
Prints all the prime number equal to or less than the number given in nloglogn time complexity using the Sieve of Eratosthenes algorithm.
=>  Sieve of Eratosthenes

Currency Converter, Rock paper Scissors
This is a most popular game of Rock paper Scissors
=> Rock paper Scissors

Check for Power of 2
checks, whether the number entered, is the power of 2 or not in O(1) time complexity using bit manipulation technique.
=> Check for Power of 2

Find the Largest and Smallest Elements in an Array
A much faster and easy to implement way to find the largest and smallest elements in an array
=> Create  Find the Largest and Smallest Elements in an Array

code to find ASCII value of character
An efficient program to find the ASCII value of any character in c++.
=> Create  code to find ASCII value of character

Program to find sum of  elements of array
An efficient and  fast method to find the sum of array elements ,especially easy to understand .
=> Create  Program to find sum of  elements of array

Program to check if number is Even or Odd
It is the fastest method to know whether a number is odd or even because it uses bitwise operator " & ".
=> Create  Program to check if number is Even or Odd

Program to check triangle is equilateral, isosceles or scalene
Efficient and easy to understand code to check triangle is equilateral, isosceles or scalene in c++ language.
=> Create Program to check triangle is equilateral, isosceles or scalene

#include <math.h> #include <stdio.h> int convert(long long n); int main() {     long long n;     printf("Enter a binary number: ");     scanf("%lld", &n);     printf("%lld in binary = %d in decimal", n, convert(n));     return 0; }  int convert(long long n) {     int dec = 0, i = 0, rem;     while (n != 0) {         rem = n % 10;         n/binary to decimal conversion c program
optimized code for binary to decimal conversion
=> Create binary to decimal conversion c program

binary to octal conversion c program
optimized code for binary to octal conversion in C
=> Create binary to octal conversion c program

Program to find power of number
An easy to understand  program in c++ to find the power of any number without using any function from library.
=> Create Program to find power of number

to print fibonacci series upto n
optimized code to print fibonacci series till n
=> Create to print fibonacci series upto n

program to find whether triangle is isosceles scalene or equilateral in C
optimized code to find whether given triangle with three sides is equilateral, scalene,or isosceles
=> Create program to find whether triangle is isosceles scalene or equilateral in C

count sum of elements in array, leap year or not, leap year or not program, palindrome.py, string_palindrome.py
=> Create count sum of elements in array

to find power of a number in c
optimized code to find power of number in C
=> Create to find power of a number in c

length of string program
=> Create length of string program

Program to print leap years in given range in c++
Optimized for Program to print leap years in a given range
=> Create Program to print leap years in given range in c++

Find Factorial of a given number
Optimized Find Factorial of a given number
=> Create Find Factorial of a given number

Program to calculate power of number
Optimized Program to calculate the power of the number
=> Program to calculate power of number

Program to convert binary to decimal number (Problem Statement)
Optimized Program to convert binary to decimal number
=> Program to convert binary to decimal number

Create Counting number of digits in integers
Fastest and efficient method to implement the program in c++.
=> Create Create Counting number of digits in integers

C++ program to sort in descending order
Beginner friendly and easy to implement code in c++.
=> Create C++ program to sort in descending order

Create Code for factorial of the given number
recursive function to find the factorial of a number in the fastest manner in c++.
=> Create Create Code for factorial of the given number

Create a Fibonacci series
Easy to understand and implement in c++ language ,helpful for easy understanding .
=> Create Create a Fibonacci series

Create a C++ program to sort an array in Ascending Order
Less lined ,easy to understand code in c++ using library .
=> Create Create a C++ program to sort an array in Ascending Order

Create a Max value in a array
used algorithm library for lesser lines of code , easy  to implement ,helpful in competitive programming.
=> Create Create a Max value in a array

Program a to find lenght of a string
Optimal solution  in c++ to find the length of a string .
=> Create Program a to find lenght of a string

Program_to_print_leap_years/leap year detection
finding the leap year using python
=> leap year detection from python

Create Count of distinct elements in an array
Easiest way to count the distinct elements in array in c++ using the set library .
Helpful in competitive coding .
=> Create Create Count of distinct elements in an array

Create Count the no. of setbits in number
Fast and efficient code to find the no. of setbits in a number.
=> Create Create Count the no. of setbits in number

Program to find smallest element in a array
used sort function to sort and found the no. at oth index as the smallest element in the array.
=> Create Program to find smallest element in a array

Create Program to find the sum of  an array elements
Used the accumulate function from c++ library for faster and less lined program .
=> Create Create Program to find the sum of  an array elements

program to convert binary to decimal number using java.
=> Create program to convert binary to decimal number using java.

Program to find factorial of number in Python
Optimized code to find the factorial of a number in Python.
=> Create Program to find factorial of number in Python

Sum of numbers in array
Optimized Code For Getting Sum of numbers in array quickly
=> Create Sum of numbers in array

Perform all arithematic operators
Optimized  Code For Perform all arithematic operators quickly
=> Create Perform all arithematic operators

Fibonacci Series Print
Optimized Code For Fibonacci Series Print quickly
=> Create Fibonacci Series Print

SIDHANT_THAKUR_intermediate_prblm_solutions/addition of 2D or 3D matrices
This program performs the addition of two 2D or 3D matrices.
=> created program for addition of 2D or 3D matrices

SIDHANT_THAKUR_intermediate_prblm_solutions/reversing array
this program creates an array and reverses its elements order.
=> Program to reverse order of elemnts in array

program to display fibonacci series
optimized code for displaying fibonacci series
=> Create program to display fibonacci series

C  program to find power of any number
optimized code for calculating power of a number
=> Create  C  program to find power of any number

Calculator for add,sub,mul and divide
Code for Add,Subtract,Multiply and Divide two numbers
=> Create Calculator for add,sub,mul and divide

Create C++ code to find ascii value of character
A precise code for finding the ASCII value in c++ language.
=> Create Create C++ code to find ascii value of character

Create Display Largest Element of an array
An easy to execute solution in c++.
=> Create Create Display Largest Element of an array

Create CPP program to find smallest element in array
Wrote the code in c++,using the library function -> *min_element(a,a+n).
=> Create Create CPP program to find smallest element in array

Create Create Count the no. of setbits in number
Easy code to find the number of set_bits in a number in c++ language using while loop and " & " operator.
=> Create Create Create Count the no. of setbits in number

prg sum of elements in array
Optimized code for sum of elements in an array
=> Create  prg sum of elements in array

Length of a string(js).md
Kindly review the pull request made on easy question.
=> Create Length of a string(js).md

find the smallest element in array, smallest number find in array
optimize the code smallest number in array
=> find the smallest number in array

Create C Program to Swap Two Numbers(using pointer)
swapping two number(using pointer)
=> Create  Create C Program to Swap Two Numbers(using pointer)

reverse of numbers in given range
Readable and understandable C ++ code to reverse numbers in a given range.
=> Create reverse of numbers in given range

Create Creating a linked list(user control)
user control create link list program
=> Create Create Creating a linked list(user control)

Program to find factorial of number with C++
Optimized and easy way to find factorial of a number
=> Create Program to find factorial of number with C++

Python program for inorder and preorder Traversal
Simple python program to implement inorder and preorder traversal on given array of characters.
=> Create Python program for inorder and preorder Traversal

Program to print Fibonnaci Series in C++
method to calculate Fibonacci series in C++ language
=> Create Program to print Fibonnaci Series in C++

Program to count sum of all numbers in array in C++
Easy code to calculate sum of elements in array in C++
=> Create Program to count sum of all numbers in array in C++

7.Program to count sum of all numbers in array
My solution in Javascript for the proposed problem.
=> Count sum of all numbers in array

2.Problem to find the largest element in array
=> Create program to find the largest element in array

Find the smallest element in array
=> Program to find the smallest element in array

SIDHANT_THAKUR_ADVANCED_PROBLEM_SOLUTIONS/BINARY_TO_DECIMAL_CONVERSION
This program converts binary number to a decimal number .
=> created BINARY_TO_DECIMAL_CONVERSION program

SIDHANT_ADVANCED_PROBLEM_SOLUTIONS/2D&3DMATRIX_MULTIPLICATION.cpp
THIS PROGRAM MULTIPLY 2 MATRIX AND PRINT THEIR RESULT.
=> created 2D&3DMATRIX_MULTIPLICATION.cpp

C++/Even or odd.cpp
Optimized code for even or odd
=> Create Even or odd.cpp

Python/pascal's triangle.py
Optimized code for pascal's triangle
=> Create pascal's triangle.py

sum of element in the list
optimized the code sum of elements in the  list
=> Create sum of element in the list

calculate the length of string
optimized the code calculate the length of string
=> Create calculate the length of string

C/prime or not.c
optimized code for prime numbers
=> Create prime or not.c

program is to factorial of a number
=> Create program is to factorial of a number

find the factorial of number
Optimized code for getting the factorial of a number in simple steps and very quickly.
=> Create find the factorial of number

smallest element in the array
Optimized changes in finding the smallest element in an array in a easy way.
=> Create smallest element in the array

addition of any multidimensional matrices
Optimized changes to find the sum of any multidimensional matrices(2D or 3D) quickly.
=> Create addition of any multidimensional matrices

Check armstrong number.cc
**Armstrong number** is a number that is equal to the sum of cubes of its digits.
=> Create C++ code to check armstrong number

Python Program for Bubble Sort.py
This Python program allows the user to enter the List Size. Next, we are using For Loop to insert elements into the List. After that, we are sorting the list items using the Python bubble sort algorithm.
=> Python Program for Bubble Sort

sum of array with recursion
we optimized the code for sum of the array using recursion.
=> Create sum of array with recursion

Stone-Paper-Scissor/game.py
Created stone-paper-scissor game based on python language with random() function for computer AI.
=> Create stone-paper-scissor game.py

DP-Maximum Product Cutting
Dynamic Programming solution of Maximum product cutting question.
=> Create DP-Maximum Product Cutting

Maximum Sum such that NO 2 elements are adjacent
Using the inclusion and exclusion principle to find out the maximum sum s.t. no 2 elements are adjacent.
=> Maximum Sum such that NO 2 elements are adjacent

Print All permuations of a given string contains NO duplicates
C++ Program for generating all permutations of a given string contains NO duplicates.
=> C++ Program to Print All permutations of a given string contains NO duplicates

Dynamic Programming - Subset Sum Problem
C++ Program to to find whether the subset is possible with the given sum
=> Dynamic Programming - Subset Sum Problem

task-management/app.py
Added task management application based on python application.
=> Create Task management application

Convert Binary to Octal using c++
Converting a binary number to Octal number
=> Create Convert Binary to Octal using c++

Multiply 2D matrix in c++
=> Create Multiply 2D matrix in c++

sum of numbers in array(c++)
=> Create sum of numbers in array(c++)

finding even or odd numbers
code for finding even or odd numbers .
=> Create finding even or odd numbers

C++/Even or odd.cpp
updated code with explanation through comments and intended the code
=> Update Even or odd.cpp

reverse string (c++)
optimized code to reverse a string with explanation.
=> Create reverse string (c++)

Doubly Lkinked List in C
Program to Create, Insert (in beginning, at position, at end) ,Delete (in beginning, at position, at end) and Display elements of Doubly Linked List in C
=> Doubly Linked List in C

Circular Linked List in C
Program to Create, Insert (in beginning, at position, at end) ,Delete (in beginning, at position, at end) and Display elements of Circular Linked List in C
=> Circular Linked List in C

Circular Doubly Linked List in C
Program to Create, Insert (in beginning, at position, at end) ,Delete (in beginning, at position, at end) and Display elements of Circular Doubly Linked List in C
=> Circular Doubly Linked List in C

Pirority Queue in C
Program to Create Pirority Queue in C (Enqueue, Dequeue and Display)
=> Pirority Queue in C

Circular Queue in C
Program to create Circular Queue in C (Enqueue, Dequeue and Display)
=> Circular Queue in C

Arithmetic Operation
Arithmetic Operation using c++
=> Create Arithmetic Operation

Program to sort an array in ascending order in python language
best way to sort an array in ascending order in python
=> Create Program to sort an array in ascending order in python language

List-Manipulation/List-Manipulation.py, List-Manipulation/List_manipulation_1.py, List-Manipulation/List_manipulation_2.py, List-Manipulation/List_manipulation_3.py, List-Manipulation/List_manipulation_4.py, List-Manipulation/List_manipulation_5.py, List-Manipulation/List_manipulation_6.py
Added List Manipulation Application based on list ([]) with import of (user defined) modules in python language.
=> Added List Manipulation Application

Program to reverse the array in Python Language
the best way to reverse the array in Python
=> Create Program to reverse the array in Python Language

Program to print prime numbers in given range in python language
the best way to find prime numbers with given 2 parameters lower and higher number in python
=> Create Program to print prime numbers in given range in python language

Program to calculate power of number python language
the best way to calculate power of number python language
=> Create Program to calculate power of number python language

CPP program to find String Permutations
Simple and easy program to find String Permutations
=> Create CPP program to find String Permutations

Python program to find substrings of a given string
This program will print substrings of the given string with their frequencies of occurring.
=> Create Python program to find substrings of a given string

array adding
=> adding two array

arm strong number in c
=>  armstromg in strong number on c

stack in c
=> stack program in c

calculator program in c
calculator making in c program
=> calculator program in c

java program to reverse a number
optimized code for reversing a number in java
=> Create java program to reverse a number

String-Manipulation/STRING-MANIPULATION.py, String-Manipulation/String_manipulation_1.py, String-Manipulation/String_manipulation_2.py, String-Manipulation/String_manipulation_3.py, String-Manipulation/String_manipulation_4.py
Added String Manipulation application based on python language (and 4 user-defined module imports).
=> Added String Manipulation application

Student-Records/app.py
Added student records application based on python language.
=> Added student records application.

postfix evaluation using stack
optimized code for evaluation of postfix expression
=> Create postfix evaluation using stack

java program to sort stack in ascending order
optimized code for sort stack in ascending order
=> Create java program to sort stack in ascending order

Encrypt-Decrypt/app.py
Added Encrypt-Decrypt application based on python language.
=> Added Encrypt-Decrypt application.

infix to postfix conversion algorithm in java
optimized code for infix to postfix conversion algorithm
=> Create infix to postfix conversion algorithm in java

Java Program to Find HCF and LCM of Two Numbers in Java
optimized code for calculation of HCF and LCM
=> Create Java Program to Find HCF and LCM of Two Numbers in Java

java program of switch case statement
optimized code for switch case statement
=> Create java program of switch case statement

java code for static method
code for static block and static method in java
=> Create java code for static method

java program for Queue methods
optimize  code for simple queue implementation.
=> Create java program for Queue methods

Create Binary to Decimal
Optimized Code For Getting  Binary to Decimal
=> Create Create Binary to Decimal

Create C Program for Febonacci Siries
Optimized code for getting Create C Program for Febonacci Siries.
=> Create Create C Program for Febonacci Siries

MatrixMultiplication.c
I have added the code for matrix multiplication of multi-dimensional array.
Thank you
=> Matrix Multiplication

ASCII_Finder.c
I have added code for finding ASCII of given character
=> Created ASCII_Finder.c

Create Code to Find Factorial of A Number
Optimized the code for getting Create Code to Find Factorial of A Number.
=> Create Create Code to Find Factorial of A Number

Create Armstrong Number in C
Optimized the code for getting Armstrong Number in C.
=> Create Create Armstrong Number in C

Consonant&VowelCounter.c
Created A program for counting vowels & consonants
=> Vowels & consonants counter

BinToDec.c
It converts Binary to decimal no
=> Created BinToDec.c

Program to find length of String using JAVA
Program to find the length of String using JAVA, implementation is also described.
=> Create Program to find length of String using JAVA

FunnyString.py
It's a problem for hackerrank, will be useful! Used my own logic!
=> created funnystring.py for hacktoberfest2020

Program of Matrix Subtraction 2 D
optimized Program of Matrix Subtraction 2 D
=> Hacktoberfest- Create Program of Matrix Subtraction 2 D

Program in java to calculate power of number
optimized Program in java to calculate power of number
=> Hacktoberfest- Create Program in java to calculate power of number

Python Program to find the factors of a number
Optimized Python Program to find the factors of a number
=> Hacktoberfest- Create Python Program to find the factors of a number

JAVA Program to find Factorial
JAVA program to find Factorial
=> Create JAVA Program to find Factorial

SelectionSort.java
Selection sort is an algorithm that selects the smallest element from an unsorted list in each iteration and places that element at the beginning of the unsorted list.
=> SelectionSort

JAVA Program to calculate power of a number
JAVA Program to calculate power of a number
=> Create JAVA Program to calculate power of a number

JAVA program to print prime number with given range
Program to print  prime number between 1 to 50
=> Create JAVA program to print prime number with given range

Odd or Even.cpp
Optimised Solution for finding if the given number is Odd or even in C++
=> Create Odd or Even.cpp

Matrice addition in Java
A method that adds two matrices if they have the same size
=> Create matrice addition in Java

C Program to Check Prime or Armstrong Number Using User-defined Function
Added C Implementation of Create C Program to Check Prime or Armstrong Number Using User-defined Function/
=> Create C Program to Check Prime or Armstrong Number Using User-defined Function

program to count sum of all numbers in array, program to fine factorial of number in C, sum of element in array
optimized code for getting sum of elements in array quickly
=> Create sum of element in array

Create the Binary to Decimal
Optimized the code for getting Binary to Decimal.
=> Create Create the Binary to Decimal

Create C Program for the Febonacci Siries
Optimized the code for getting  C Program for the Febonacci Siries.
=> Create Create C Program for the Febonacci Siries

Create Code to Find the Factorial of A Number
Optimized the code for getting to Find the Factorial of A Number.
=> Create Create Code to Find the Factorial of A Number

Create the Armstrong Number in C
Optimized the code for getting the Armstrong Number in C.
=> Create  Create the Armstrong Number in C

program to find factorial of a number using c++
program to find factorial of an array
=> Create program to find factorial of a number using c++

program to find largest element in an array using c++
=> Create program to find largest element in an array using c++

program to find smallest element in an array using c++
=> Create program to find smallest element in an array using c++

program to find length of a string using c++
=> Create program to find length of a string using c++

Champagne Tower
=> Champagne Tower

Sort Array in Ascending Order
=> Create Sort Array in Ascending Order

sum of elements in the array using recursion
Optimized code For Getting Sum of Elements in an array quickly
=> Create sum of elements in the array using recursion

The-Birthday-paradox Problem.cpp
How many people must be there in a room to make the probability 100% that at-least two people in the room have same birthday?
Answer: 367 (since there are 366 possible birthdays, including February 29).
How many people must be there in a room to make the probability 50% that at-least two people in the room have same birthday?
Answer: 23
The number is surprisingly very low. In fact, we need only 70 people to make the probability 99.9 %.
=> The-Birthday-paradox Problem.cpp

stack use c
=> stack program

simple game program in c
=> mind reader game

a program to find length of a string using c++
=> Create a program to find length of a string using c++

a program to find smallest element in an array using c++
=> Create a program to find smallest element in an array using c++

calender in c
=> calendar programs in   c

a program to find largest element in an array using c++
=> Create a program to find largest element in an array using c++

a program to find factorial of a number using c++
=> Create a program to find factorial of a number using c++

counter
=> counter program in c

Rock paper scissors lizard and spock
Here is Rock paper scissors lizard and Spock game. Play and enjoy.
=> Create Rock paper scissors lizard and spock

Recursive Program to reverse the array
Recursive Python program to reverse any given array.
=> Create Recursive Program to reverse the array.py

Program to print prime numbers in given range.py
Created a function called prime_range that takes lower and upper limit and returns a list of prime numbers.
=> Create Program to print prime numbers in given range.py

Program to print Fibonnaci Series.py
Optimized Fibonacci Series using bottom-up DP.
=> Create Program to print Fibonnaci Series.py

Program to calculate count of vowels & consonants in string.py
=> Create Program to calculate count of vowels & consonants in string.py

Program to convert binary to decimal number.py
One line Python function using inbuilt int function.
=> Create Program to convert binary to decimal number.py

Armstrong Number in C++
Hey this is Praduman. I have made a c++ program to check armstrong number.
=> Create Armstrong Number in C++

Cartesian Product of Numbers.py
Get all possible combinations of numbers to a certain degree
=> Cartesian Product of Numbers to any degree

Program to find lenght of  a string in c ++, Program to sort given array (ascending & descending)
the most easy  Program to find lenght of  a string in c ++
=> Create Program to find lenght of  a string in c ++

sum of element in an array
Code to get the sum of elements of an array
=> Create sum of element in an array

C++/Even or odd
Code to return number type as odd/even
=> Create Even or odd

program to find factorial of anumber
#include<stdio.h>  
int main()    
{    
int i,fact=1,number;    
printf("Enter a number: ");    
scanf("%d",&number);    
for(i=1;i<=number;i++){    
fact=fact*i;    
}    
printf("Factorial of %d is: %d",number,fact);    
return 0;  
}
=> Create program to find factorial of anumber

darkmode_website.html
Hey I had added a css and javascript page ,which you can toggle darkmode and lightmode in the webpage. You can create awsome darkmode websites
=> Darkmode and Lightmode toggle website

java program to print * in right triangle
optimized code for printing * in right triangle pattern
=> Create java program to print * in right triangle

fossai game
=> fossai game in phython

pong game
=> pong game in phython

tiles
=> tiles gametiles

Height of BST
=> Create Height of BST

analog_clock.html
Checkout this analog clock made by simple css and javascript. perfect running. can add to any website.
=> Analog clock using css and javascript

Program to Check Prime Number.py
added the code of checking prime number in python.
=> Create check prime number

Check element is prime or not
Optimized code to check if element is prime or not
=> Create Check element is prime or not

Calculate count of vowels and consonants in a string
Python program to count the vowels and consonants.
=> Create Calculate count of vowels and consonants in a string

decimal to binary and binary to decimal
Python code for the conversion of decimal to binary and vice versa
=> Create decimal to binary and binary to decimal

Swaping in c
=> Create Swaping in c

Floyd'sTriangle
=> Floyd's Triangle.c

Matrix Multiplication.c
Added a code for matrix multiplication
=> Matrix Multiplication.c

Leap Year.cpp
Created a program for checking a leap year in c++
=> Leap Year.cpp

Kadanes Alogorithm
Added a code for kadane algorithms
=> Kadane'sAlogorithm.cpp

calculate all arithmetic operations
python program to perform all operations
=> Create calculate all arithmetic operations

To Check Vowel or consonant
C program to Check Vowel or consonant
=> Create To Check Vowel or consonant

To check Alphabet or not
C Program to Check Whether a Character is an Alphabet or not
=> Create To check Alphabet or not

Factors of a Positive Integer
Factors of a Positive Integer using C
=> Create Factors of a Positive Integer

RockPaperScissors.py
A program to play Rock, Paper, Scissors.
=> Rock, Paper, Scissors.

programe_to_ print _prime_ numbers.py
This program prints the prime numbers between a range of numbers and returns the lenght
=> Programme to print primes

Terminate the timer thread
=> Create Terminate the timer thread

count the total number of characters in a string
=> Create count the total number of characters in a string

sum of the factorials
=> Create sum of the factorials

Word Count
I am trying to make a program on word count
=> Create Word Count

slideshow_webpage.html
here added an automatic slideshow banner using javascript and css, added 5 no copyright images, which will slide after every 1 second. you can change the time
=> Automatic slideshow banner for  website

digitalclock.html
digital clock with dark background, the sconds will animate automatically .
=> Animated Digital clock 

C++ Program to Calculate Standard Deviation
=> Create C++ Program to Calculate Standard Deviation

C++ Program to Calculate Average of Numbers Using Arrays
=> Create C++ Program to Calculate Average of Numbers Using Arrays

C++ Program to Convert Binary Number to Octal and vice-versa
I am Pawan your subscriber. Please accept all 4 PR.
=> Create C++ Program to Convert Binary Number to Octal and vice-versa

Factorial of number using recursion
=> Create Factorial of number using recursion

Sum of elements of an array
The Python code to calculate the sum of elements easily.
=> Calculating the sum of elements of an array

program to find largest element of array
good code to find largest element of array
=> Create program to find largest element of array

program to find smallest element of array
good code to find smallest element of array
=> Create program to find smallest element of array

Program to check whether a number is prime
Python program to check whether a number is prime or not easily.
=> Create Program to check whether a number is prime

Check even or odd
Python program to check whether a number is even or odd.
=> Even or odd check

Tic Ta Toe
Code to play tic ta toe game in C program
=> Create Tic Ta Toe

Program on Leap Year
Optimized code for checking whether a given year is a leap year or not in Python
=> Create Program on Leap Year

C++ Program to Add Two Distances (in inch-feet) System Using Structures
Your subscriber.
hactoberfest-accepted
=> Create C++ Program to Add Two Distances (in inch-feet) System Using Structure

C++ Program to Add Complex Numbers by Passing Structure to a Function
=> Create C++ Program to Add Complex Numbers by Passing Structure to a Function

C++ Program to Calculate Difference Between Two Time Period
=> Create C++ Program to Calculate Difference Between Two Time Period

C++ Program to Store and Display Information Using Structure
I am your fan.I am your subcriber.
Please accept all 4 PR.
=> Create C++ Program to Store and Display Information Using Structure

Sorting array in ascending order
Code for sorting array in ascending order in C++
=> Create Sorting array in ascending order

BMI calculater
=> BMI calculater

String Reverse
Program to reverse a string in C language
=> Create String Reverse

Binary Search in C++
Optimized code for Binary Searching in C++
=> Create Binary Search in C++

Matrix Addition
Program to perform Matrix Addition in C
=> Create Matrix Addition

Program to find Largest Element in an array
Program to find the Largest Element in an array
=> Python Program to find Largest Element in an array

Fibonacci series in python
Code for fibonacci series in python
=> Create Fibonacci series in python

whether a number is even or add
Python Code to find whether a number is odd or even
=> Create whether a number is even or add

finding average of n number using function in c
optimized program for finding average of n numbers
=> Create finding average of n number using function in c

C++ program for Longest common subsequence
This program finds the length of longest common subsequence using dynamic programming.
=> Create C++ program for Longest common subsequence

Decimal to Binary conversion
I have already raised an issue for this problem. Kindly assign this issue to me.
=> Create Decimal to Binary conversion

Pallindrome number in C++
I have already raised an issue for this problem and tried to provide the simplest solution. Please assign this issue to me.
=> Create Pallindrome number in C++

Selection Sort C++
Selection sort using function calling in C++.
=> Create Selection Sort C++

BubbleSort C++
Made a function for Bubble Sorting an array and called it in our main function.
=> Create BubbleSort C++

Check Armstrong Number
Java program for check a no Amstrong or not
=> Create  Check Armstrong Number

Python | Validating phone numbers
Validating phone numbers.
Let's dive into the interesting topic of regular expressions! You are given some input, and you are required to check whether they are valid mobile numbers.
A valid mobile number is a ten digit number starting with a  7,8 or 9.
=> Create Python | Validating phone numbers

Factorial of a Number
Java program for find factorial of a integer
=> Create  Factorial of a Number

Python | Validating and Parsing Email Addresses
Validating and Parsing Email Addresses.
=> Create Python | Validating and Parsing Email Addresses

Python | Calendar Module.py
The calendar module allows you to output calendars and provides additional useful functions for them.
=> Create Python | Calendar Module.py

Alphabet Rangoli.py
Creation of Alphabet Rangoli after giving an integer. Your task is to print an alphabet Rangoli of size . (Rangoli is a form of Indian folk art based on creation of patterns.)
=> Create Alphabet Rangoli.py

Python | Query Processing For Distributed Database
To implement Query Processing for distributed Databases.
=> Create Python | Query Processing For Distributed Database

Prime numbers in given range
C++ code to print prime numbers in a given range
=> Create Prime numbers in given range

Count of vowels and consonants in a string
Counting vowels and consonants in a string C++
=> Create Count of vowels and consonants in a string

Check Leap Year
Java program for Checking Leap year
=> Create  Check Leap Year

to check whether a number is prime or not
code to find whether a number is prime or not
=> Create to check whether a number is prime or not

C++ Program to Check Armstrong Number
Program to Check Armstrong Number
=> Create C++ Program to Check Armstrong Number

Java applet Grid layout
=> Java Grid layout (applet)

Java applet IRCTC
Java applet with basic functions like inputting name source destination etc from the user. Editor used: Visual Studio.
=> Java Applet

Assignment Operators
Python Assignment Operators Example
=> Assignment Operators

Bitwise Operators
Python Bitwise Operators Example
=> Bitwise Operators

Classes in Java
Shows various features of java- inheritance , polymorphism.
=> Java- area calculation

Logical Operators
Java Logical Operators Example
=> Logical Operators

Java Operations
Java Arithmetic Operators using Float
=> Java Operations

Largest Number
C Program to Find Largest of Two Numbers using Switch Case
=> Largest Number

Quicksort implementation in C
Quicksort implementation in C using divide and conquer algorithm
=> Quicksort implementation in C

Finding Bitonic point in Bitonic sequence
This is the optimal solution for finding Bitonic point in Bitonic sequence
=> Finding bitonic point in bitonic sequence

Fractional Knapsack Problem
This is the solution to the Fractional Knapsack  problem using a greedy algorithm
=> Solution of Fractional Knapsack problem

Cube Number
C Program to Calculate Cube of a Number
=> Cube Number

The program to find a factor of a number
=> Create The program to find a factor of a number

Type Conversion in Java
The program converts int to double , double to int , double to byte , Int to String , String to int in java.
=> Type Conversion in Java

find smallest element in array
=> Create find smallest element in array

To find GCD of two number
easy solution for find gcd of two number
=> Create To find GCD of two number

Check Whether a Character is Alphabet or Not
Java program for checking Whether a Character is Alphabet or Not
=> Create Check Whether a Character is Alphabet or Not

Python | Time Delta
When users post an update on social media,such as a URL, image, status update etc., other users in their network are able to view this new post on their news feed. Users can also see exactly when the post was published, i.e, how many hours, minutes or seconds ago.
Since sometimes posts are published and viewed in different time zones, this can be confusing. You are given two timestamps of one such post that a user can see on his newsfeed in the following format:
Day dd Mon yyyy hh:mm:ss +xxxx
Here +xxxx represents the time zone. Your task is to print the absolute difference (in seconds) between them.
Input Format
The first line contains T, the number of testcases.
Each testcase contains 2 lines, representing time t1 and time t2.
Constraints
Input contains only valid timestamps
year<=3000. …
=> Create Python | Time Delta

finding the factorial of a number with python
optimized a code for finding the factorial of a number
=> Create finding the factorial of a number with python

finding the maximum & minimum numbers in the list with python
optimized code for finding the maximum & minimum numbers in the list with python
=> Create finding the maximum & minimum numbers in the list with python

Convert Binary To Decimal
optimized code for converting  Binary number To Decimal number
=> Create Convert Binary To Decimal

Return ASCII Values
This is an alternative solution to printing ASCII Values in C++ where either a character or a number can be converted to its ASCII decimal value.
=> Create Return ASCII Values

Even and Odd for Randomly Generated Values
This program is a solution to finding out if a randomly generated number (in this case it's a random number between 0 and 5) is even or odd.
=> Create Even and Odd for Randomly Generated Values

oddeven.js, powercalc.js
Added an Odd or Even in JavaScript, requires node.js to be installed to run in terminal
=> Odd or Even in JavaScript

AdEx_Neuron_model.py
The code is made to model an AdEx neuron. The code was made in a study on computational neuroscience.
=> AdEx Neuron model.

Convert Decimal to Binary in JS
This is a simple way to convert decimal to binary in js
=> Convert Decimal to Binary in JS

Swapping two Numbers using a Temporary Variable
=> Create Swapping two Numbers using a Temporary Variable

optimised: factorial of a number
=> Create optimised: factorial of a number

optimised: sum of an array
=> Create optimised: sum of an array

optimised: Swap 2 numbers
=> Create optimised: Swap 2 numbers

Java Program to Find the Biggest of 3 Numbers « Prev Next » This is a Java Program to Find the Biggest of 3 Numbers.
this is a Java Program to Find the Biggest of 3 Numbers.
=> Create  Java Program to Find the Biggest of 3 Numbers 

hospitalform
A hospital form for patients and hospitals by using python and Mysql workbench
=> Create hospital form

Addition of two numbers without using + operator
Python program to add two numbers without using plus operator
=> Addition of two numbers without using + operator

Subtraction of two numbers without using - operator
Python program to subtract a number from another number without using minus (-) operator
=> Subtraction of two numbers without using - operator

Division of two numbers without using division operator
Python program to perform division of two numbers without using division operator
=> Division of two numbers without using division operator

Multiply two numbers without using * operator
Python program to multiply two numbers without using multiplication operator
=> Multiply two numbers without using * operator

number-conversion.js
Convert Decimal to binary, octal and hexadecimal by javascript
=> Number Conversion in js

Sum of element in array php
Code for sum of the element in array PHP.
=> Create Sum of element in array php

Count the Number of Occurrence of an Element in an Array
Count the Number of Element in an Array (Java).
=> Create Count the Number of Occurrence of an Element in an Array

Create C++ Program to Calculate Average of Numbers Using Arrays
optimized code for calculating average of numbers using arrays .
=> Create Create C++ Program to Calculate Average of Numbers Using Arrays

Factorial program in python for loop
Program python to find factorial number by for loop.
=> Create Factorial program in python for loop

Factorial program in python recursion
Python factorial program by recursion.
=> Create Factorial program in python recursion

Create Fibonacci Series Using C
optimized program for creating fibonacci series using C .
=> Create Create Fibonacci Series Using C

Lenght of a String in Python
Code to find the lenght of a String in Python.
=> Create Lenght of a String in Python

Create Floyd's triangle
optimized code for Floyd's triangle using C
=> Create Create Floyd's triangle

Create Height of BST
Find the height of a binary tree using C++
=> Create Create Height of BST

Create QuickSort
Optimized code for create Quick Sort using Java.
=> Create Create QuickSort

Create Selection Sort C++
optimized code for create Selection Sort C++
=> Create Create Selection Sort C++

Smallest element in array in Python
Python Code to find the smallest element in a given array.
=> Create Smallest element in array in Python

Prime Numbers in given range in Python
Code to print prime numbers in a given range.
=> Create Prime Numbers in given range in Python

Calculate Power of a Number in Python
Code to calculate power of a number using Python.
=> Create Calculate Power of a Number in Python

factorial.js
Created factorial.js to be approved
=> Created factorial.js
